# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bath_tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1039, 725)
        mainWindow.setStyleSheet("QMainWindow#MainWindow\n"
"{\n"
"background-color:rgb(200, 200, 200);\n"
"}    \n"
"")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dockWidget = QtWidgets.QDockWidget(self.centralwidget)
        self.dockWidget.setStyleSheet("QScrollBar:vertical {\n"
"border: 0px ;\n"
"background-color:rgb(60, 60, 60);\n"
"width:6px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"background:rgb(225,225, 225);\n"
"min-height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"background: rgb(255, 0, 0);\n"
"       height: 0px;\n"
"     subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"#QScrollBar::sub-line:vertical {\n"
" background: rgb(0, 255, 17);\n"
"    height: 0 px;\n"
"     subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"    }\n"
"\n"
"QScrollBar:horizontal {\n"
"border: 0px ;\n"
"background-color:rgb(60, 60, 60);\n"
"\n"
"height:6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"background:rgb(225,225, 225);\n"
"min-width:0px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"background: rgb(255, 0, 0);\n"
"       width: 0px;\n"
"     subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"#QScrollBar::sub-line:horizontal{\n"
" background: rgb(0, 255, 17);\n"
"    width:0px;\n"
"     subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"    }")
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetFloatable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_31.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.frame_19 = QtWidgets.QFrame(self.dockWidgetContents)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout.setContentsMargins(0, 0, 0, 9)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setSpacing(0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.verticalLayout.addWidget(self.frame_20)
        self.Menu_Right = QtWidgets.QTreeWidget(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Menu_Right.sizePolicy().hasHeightForWidth())
        self.Menu_Right.setSizePolicy(sizePolicy)
        self.Menu_Right.setMinimumSize(QtCore.QSize(90, 0))
        self.Menu_Right.setMaximumSize(QtCore.QSize(90, 16777215))
        self.Menu_Right.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Menu_Right.setStyleSheet("QTreeWidget\n"
"{\n"
"background-color:transparent;\n"
"color:rgb(255, 255, 255);\n"
"border: 0px solid rgb(17, 17, 17);\n"
"border-radius: 6px;\n"
"}    \n"
"QTreeWidget::item {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left;\n"
" height: 120px;\n"
"border-radius: 12px;\n"
"}\n"
"QTreeWidget::item:hover {\n"
"    background-color: rgb(52, 95, 251);\n"
"border-radius: 12px;\n"
"}\n"
"QTreeWidget::item:pressed {\n"
"    background-color: rgb(10, 50, 205);\n"
"    border-style: inset;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"\n"
"QTreeWidget::item:selected {\n"
"    background-color:rgb(40, 105, 254);\n"
"    border-style: inset;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"border: 0px ;\n"
"background-color:rgb(60, 60, 60);\n"
"width:6px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"background:rgb(225,225, 225);\n"
"min-height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"background: rgb(255, 0, 0);\n"
"       height: 0px;\n"
"     subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"#QScrollBar::sub-line:vertical {\n"
" background: rgb(0, 255, 17);\n"
"    height: 0 px;\n"
"     subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"    }\n"
"\n"
"QScrollBar:horizontal {\n"
"border: 0px ;\n"
"background-color:rgb(60, 60, 60);\n"
"\n"
"height:6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"background:rgb(225,225, 225);\n"
"min-width:0px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"background: rgb(255, 0, 0);\n"
"       width: 0px;\n"
"     subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"#QScrollBar::sub-line:horizontal{\n"
" background: rgb(0, 255, 17);\n"
"    width:0px;\n"
"     subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"    }\n"
"")
        self.Menu_Right.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Menu_Right.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Menu_Right.setAutoScroll(True)
        self.Menu_Right.setAutoScrollMargin(0)
        self.Menu_Right.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.Menu_Right.setIndentation(0)
        self.Menu_Right.setAnimated(True)
        self.Menu_Right.setHeaderHidden(True)
        self.Menu_Right.setColumnCount(1)
        self.Menu_Right.setObjectName("Menu_Right")
        item_0 = QtWidgets.QTreeWidgetItem(self.Menu_Right)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        item_0.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.Menu_Right)
        font = QtGui.QFont()
        font.setPointSize(12)
        item_0.setFont(0, font)
        self.verticalLayout.addWidget(self.Menu_Right)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.Btn_setting = QtWidgets.QToolButton(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_setting.setFont(font)
        self.Btn_setting.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_setting.setObjectName("Btn_setting")
        self.horizontalLayout_32.addWidget(self.Btn_setting)
        self.verticalLayout.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_31.addWidget(self.frame_19)
        self.frame_anim = QtWidgets.QFrame(self.dockWidgetContents)
        self.frame_anim.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_anim.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_anim.setObjectName("frame_anim")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_anim)
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_36.setSpacing(0)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget_Anim = QtWidgets.QTabWidget(self.frame_anim)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_Anim.setFont(font)
        self.tabWidget_Anim.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget_Anim.setUsesScrollButtons(False)
        self.tabWidget_Anim.setDocumentMode(False)
        self.tabWidget_Anim.setObjectName("tabWidget_Anim")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setStyleSheet("QFrame#frame_14{\n"
"    background-color:rgb(65, 65, 65);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_29.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.groupBox = QtWidgets.QGroupBox(self.frame_14)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LEditB_max_path = QtWidgets.QLineEdit(self.groupBox)
        self.LEditB_max_path.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.LEditB_max_path.setStyleSheet("QLineEdit{\n"
"background-color:rgb(90, 90, 90);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(40, 40, 40);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"background-color:rgb(100, 100, 100);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(150, 150, 150);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:pressed {\n"
"background-color:rgb(110, 110, 110);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:nameEdit {\n"
"background-color:rgb(225, 225, 225);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:read-only{\n"
"background-color:rgb(225, 225, 225);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}\n"
"")
        self.LEditB_max_path.setText("")
        self.LEditB_max_path.setObjectName("LEditB_max_path")
        self.horizontalLayout.addWidget(self.LEditB_max_path)
        self.BtnB_max_path = QtWidgets.QToolButton(self.groupBox)
        self.BtnB_max_path.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnB_max_path.setObjectName("BtnB_max_path")
        self.horizontalLayout.addWidget(self.BtnB_max_path)
        self.BtnB_max_path_open = QtWidgets.QToolButton(self.groupBox)
        self.BtnB_max_path_open.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnB_max_path_open.setObjectName("BtnB_max_path_open")
        self.horizontalLayout.addWidget(self.BtnB_max_path_open)
        self.verticalLayout_29.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_14)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LEditB_svae_path = QtWidgets.QLineEdit(self.groupBox_2)
        self.LEditB_svae_path.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.LEditB_svae_path.setStyleSheet("QLineEdit{\n"
"background-color:rgb(90, 90, 90);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(40, 40, 40);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"background-color:rgb(100, 100, 100);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(150, 150, 150);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:pressed {\n"
"background-color:rgb(110, 110, 110);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:nameEdit {\n"
"background-color:rgb(225, 225, 225);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:read-only{\n"
"background-color:rgb(225, 225, 225);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}")
        self.LEditB_svae_path.setText("")
        self.LEditB_svae_path.setObjectName("LEditB_svae_path")
        self.horizontalLayout_3.addWidget(self.LEditB_svae_path)
        self.BtnB_svae_path_auto = QtWidgets.QToolButton(self.groupBox_2)
        self.BtnB_svae_path_auto.setObjectName("BtnB_svae_path_auto")
        self.horizontalLayout_3.addWidget(self.BtnB_svae_path_auto)
        self.BtnB_svae_path = QtWidgets.QToolButton(self.groupBox_2)
        self.BtnB_svae_path.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnB_svae_path.setObjectName("BtnB_svae_path")
        self.horizontalLayout_3.addWidget(self.BtnB_svae_path)
        self.BtnB_svae_path_open = QtWidgets.QToolButton(self.groupBox_2)
        self.BtnB_svae_path_open.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnB_svae_path_open.setObjectName("BtnB_svae_path_open")
        self.horizontalLayout_3.addWidget(self.BtnB_svae_path_open)
        self.verticalLayout_29.addWidget(self.groupBox_2)
        self.verticalLayout_2.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(18, 6, 18, 6)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.CBoxB_List_subfolder = QtWidgets.QCheckBox(self.frame_15)
        self.CBoxB_List_subfolder.setFocusPolicy(QtCore.Qt.NoFocus)
        self.CBoxB_List_subfolder.setObjectName("CBoxB_List_subfolder")
        self.horizontalLayout_24.addWidget(self.CBoxB_List_subfolder)
        self.line_4 = QtWidgets.QFrame(self.frame_15)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_24.addWidget(self.line_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem1)
        self.BtnB_List_item_delete = QtWidgets.QToolButton(self.frame_15)
        self.BtnB_List_item_delete.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnB_List_item_delete.setObjectName("BtnB_List_item_delete")
        self.horizontalLayout_24.addWidget(self.BtnB_List_item_delete)
        self.BtnB_List_item_Add = QtWidgets.QToolButton(self.frame_15)
        self.BtnB_List_item_Add.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnB_List_item_Add.setObjectName("BtnB_List_item_Add")
        self.horizontalLayout_24.addWidget(self.BtnB_List_item_Add)
        self.line_5 = QtWidgets.QFrame(self.frame_15)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_24.addWidget(self.line_5)
        self.BtnB_List_select_reverse = QtWidgets.QToolButton(self.frame_15)
        self.BtnB_List_select_reverse.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnB_List_select_reverse.setObjectName("BtnB_List_select_reverse")
        self.horizontalLayout_24.addWidget(self.BtnB_List_select_reverse)
        self.BtnB_List_select_all = QtWidgets.QToolButton(self.frame_15)
        self.BtnB_List_select_all.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnB_List_select_all.setObjectName("BtnB_List_select_all")
        self.horizontalLayout_24.addWidget(self.BtnB_List_select_all)
        self.line_6 = QtWidgets.QFrame(self.frame_15)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_24.addWidget(self.line_6)
        self.BtnB_RefreshList = QtWidgets.QToolButton(self.frame_15)
        self.BtnB_RefreshList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnB_RefreshList.setObjectName("BtnB_RefreshList")
        self.horizontalLayout_24.addWidget(self.BtnB_RefreshList)
        self.verticalLayout_30.addLayout(self.horizontalLayout_24)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame_18 = QtWidgets.QFrame(self.frame)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_29.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.frame_17 = QtWidgets.QFrame(self.frame_18)
        self.frame_17.setStyleSheet("QFrame#frame_17{\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.treeWidgetB = QtWidgets.QTreeWidget(self.frame_17)
        self.treeWidgetB.setStyleSheet("QTreeWidget\n"
"{\n"
"background-color: rgb(80, 80, 80);\n"
"color:rgb(255, 255, 255);\n"
"border: 0px solid rgb(17, 17, 17);\n"
"border-radius: 6px;\n"
"}    \n"
"QTreeWidget::item {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left;\n"
"}\n"
"QTreeWidget::item:hover {\n"
"    background-color: rgb(52, 95, 251);\n"
"}\n"
"QTreeWidget::item:pressed {\n"
"    background-color: rgb(10, 50, 205);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"\n"
"QTreeWidget::item:selected {\n"
"    background-color:rgb(40, 105, 254);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"border: 0px ;\n"
"background-color:rgb(60, 60, 60);\n"
"width:6px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"background:rgb(225,225, 225);\n"
"min-height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"background: rgb(255, 0, 0);\n"
"       height: 0px;\n"
"     subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"#QScrollBar::sub-line:vertical {\n"
" background: rgb(0, 255, 17);\n"
"    height: 0 px;\n"
"     subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"    }\n"
"\n"
"QScrollBar:horizontal {\n"
"border: 0px ;\n"
"background-color:rgb(60, 60, 60);\n"
"\n"
"height:6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"background:rgb(225,225, 225);\n"
"min-width:0px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"background: rgb(255, 0, 0);\n"
"       width: 0px;\n"
"     subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"#QScrollBar::sub-line:horizontal{\n"
" background: rgb(0, 255, 17);\n"
"    width:0px;\n"
"     subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"    }\n"
"")
        self.treeWidgetB.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeWidgetB.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeWidgetB.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeWidgetB.setIndentation(0)
        self.treeWidgetB.setObjectName("treeWidgetB")
        self.treeWidgetB.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetB)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetB)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetB)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetB)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetB)
        self.horizontalLayout_30.addWidget(self.treeWidgetB)
        self.verticalLayout_32.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_29.addWidget(self.frame_17)
        self.verticalLayout_2.addWidget(self.frame_18)
        self.frame_16 = QtWidgets.QFrame(self.frame)
        self.frame_16.setStyleSheet("QFrame#frame_16{\n"
"    background-color:rgb(65, 65, 65);\n"
"    border-radius:10px;\n"
"}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_27.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.groupBox_12 = QtWidgets.QGroupBox(self.frame_16)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.frame_21 = QtWidgets.QFrame(self.groupBox_12)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem2)
        self.radioBtnB_fbx_sn = QtWidgets.QRadioButton(self.frame_21)
        self.radioBtnB_fbx_sn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioBtnB_fbx_sn.setChecked(True)
        self.radioBtnB_fbx_sn.setObjectName("radioBtnB_fbx_sn")
        self.horizontalLayout_33.addWidget(self.radioBtnB_fbx_sn)
        self.radioBtnB_fbx_custom = QtWidgets.QRadioButton(self.frame_21)
        self.radioBtnB_fbx_custom.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioBtnB_fbx_custom.setObjectName("radioBtnB_fbx_custom")
        self.horizontalLayout_33.addWidget(self.radioBtnB_fbx_custom)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem3)
        self.verticalLayout_28.addWidget(self.frame_21)
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_12)
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem4)
        self.CBoxB_fbx_sn_export_ani_set = QtWidgets.QCheckBox(self.groupBox_13)
        self.CBoxB_fbx_sn_export_ani_set.setEnabled(True)
        self.CBoxB_fbx_sn_export_ani_set.setFocusPolicy(QtCore.Qt.NoFocus)
        self.CBoxB_fbx_sn_export_ani_set.setChecked(True)
        self.CBoxB_fbx_sn_export_ani_set.setObjectName("CBoxB_fbx_sn_export_ani_set")
        self.horizontalLayout_35.addWidget(self.CBoxB_fbx_sn_export_ani_set)
        self.CBoxB_fbx_sn_root_zero = QtWidgets.QCheckBox(self.groupBox_13)
        self.CBoxB_fbx_sn_root_zero.setFocusPolicy(QtCore.Qt.NoFocus)
        self.CBoxB_fbx_sn_root_zero.setChecked(True)
        self.CBoxB_fbx_sn_root_zero.setObjectName("CBoxB_fbx_sn_root_zero")
        self.horizontalLayout_35.addWidget(self.CBoxB_fbx_sn_root_zero)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem5)
        self.verticalLayout_38.addLayout(self.horizontalLayout_35)
        self.verticalLayout_28.addWidget(self.groupBox_13)
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_12)
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_15.setObjectName("groupBox_15")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.radioBtnB_fbx_custom_set = QtWidgets.QRadioButton(self.groupBox_15)
        self.radioBtnB_fbx_custom_set.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioBtnB_fbx_custom_set.setChecked(True)
        self.radioBtnB_fbx_custom_set.setObjectName("radioBtnB_fbx_custom_set")
        self.verticalLayout_33.addWidget(self.radioBtnB_fbx_custom_set)
        self.radioBtnB_fbx_custom_objs = QtWidgets.QRadioButton(self.groupBox_15)
        self.radioBtnB_fbx_custom_objs.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioBtnB_fbx_custom_objs.setObjectName("radioBtnB_fbx_custom_objs")
        self.verticalLayout_33.addWidget(self.radioBtnB_fbx_custom_objs)
        self.horizontalLayout_34.addLayout(self.verticalLayout_33)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.LEditB_fbx_custom_set = QtWidgets.QLineEdit(self.groupBox_15)
        self.LEditB_fbx_custom_set.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.LEditB_fbx_custom_set.setStyleSheet("QLineEdit{\n"
"background-color:rgb(90, 90, 90);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(40, 40, 40);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"background-color:rgb(100, 100, 100);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(150, 150, 150);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:pressed {\n"
"background-color:rgb(110, 110, 110);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:nameEdit {\n"
"background-color:rgb(225, 225, 225);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:read-only{\n"
"background-color:rgb(225, 225, 225);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}\n"
"")
        self.LEditB_fbx_custom_set.setObjectName("LEditB_fbx_custom_set")
        self.verticalLayout_37.addWidget(self.LEditB_fbx_custom_set)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(15)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelB_fbx_custom_objs_count = QtWidgets.QLabel(self.groupBox_15)
        self.labelB_fbx_custom_objs_count.setText("")
        self.labelB_fbx_custom_objs_count.setObjectName("labelB_fbx_custom_objs_count")
        self.horizontalLayout_9.addWidget(self.labelB_fbx_custom_objs_count)
        self.labelB_fbx_custom_objs = QtWidgets.QLineEdit(self.groupBox_15)
        self.labelB_fbx_custom_objs.setEnabled(False)
        self.labelB_fbx_custom_objs.setStyleSheet("QLineEdit{\n"
"background-color:rgb(80, 80, 80);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(60, 60, 60);\n"
"padding: 2px;\n"
"}\n"
"\n"
"")
        self.labelB_fbx_custom_objs.setObjectName("labelB_fbx_custom_objs")
        self.horizontalLayout_9.addWidget(self.labelB_fbx_custom_objs)
        self.BtnB_fbx_custom_objs_pick = QtWidgets.QPushButton(self.groupBox_15)
        self.BtnB_fbx_custom_objs_pick.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnB_fbx_custom_objs_pick.setObjectName("BtnB_fbx_custom_objs_pick")
        self.horizontalLayout_9.addWidget(self.BtnB_fbx_custom_objs_pick)
        self.verticalLayout_37.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_34.addLayout(self.verticalLayout_37)
        self.verticalLayout_31.addWidget(self.groupBox_15)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.CBoxB_fbx_custom_backanimation = QtWidgets.QCheckBox(self.groupBox_14)
        self.CBoxB_fbx_custom_backanimation.setFocusPolicy(QtCore.Qt.NoFocus)
        self.CBoxB_fbx_custom_backanimation.setChecked(True)
        self.CBoxB_fbx_custom_backanimation.setObjectName("CBoxB_fbx_custom_backanimation")
        self.horizontalLayout_4.addWidget(self.CBoxB_fbx_custom_backanimation)
        self.CBoxB_fbx_custom_BakeResampleAnimation = QtWidgets.QCheckBox(self.groupBox_14)
        self.CBoxB_fbx_custom_BakeResampleAnimation.setFocusPolicy(QtCore.Qt.NoFocus)
        self.CBoxB_fbx_custom_BakeResampleAnimation.setChecked(True)
        self.CBoxB_fbx_custom_BakeResampleAnimation.setObjectName("CBoxB_fbx_custom_BakeResampleAnimation")
        self.horizontalLayout_4.addWidget(self.CBoxB_fbx_custom_BakeResampleAnimation)
        self.CBoxB_fbx_custom_cvfix = QtWidgets.QCheckBox(self.groupBox_14)
        self.CBoxB_fbx_custom_cvfix.setFocusPolicy(QtCore.Qt.NoFocus)
        self.CBoxB_fbx_custom_cvfix.setChecked(True)
        self.CBoxB_fbx_custom_cvfix.setObjectName("CBoxB_fbx_custom_cvfix")
        self.horizontalLayout_4.addWidget(self.CBoxB_fbx_custom_cvfix)
        spacerItem7 = QtWidgets.QSpacerItem(60, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_31.addLayout(self.horizontalLayout_4)
        self.verticalLayout_28.addWidget(self.groupBox_14)
        self.horizontalLayout_27.addWidget(self.groupBox_12)
        self.verticalLayout_2.addWidget(self.frame_16)
        self.verticalLayout_3.addWidget(self.frame)
        self.tabWidget_Anim.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.tab_3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setStyleSheet("QFrame#frame_4{\n"
"    background-color:rgb(65, 65, 65);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_13.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_6.setEnabled(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_12.setContentsMargins(9, -1, 9, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.LEditA_newSkin = QtWidgets.QLineEdit(self.groupBox_6)
        self.LEditA_newSkin.setEnabled(True)
        self.LEditA_newSkin.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.LEditA_newSkin.setFocusPolicy(QtCore.Qt.NoFocus)
        self.LEditA_newSkin.setStyleSheet("QLineEdit{\n"
"background-color:rgb(80, 80, 80);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(60, 60, 60);\n"
"padding: 2px;\n"
"}\n"
"\n"
"")
        self.LEditA_newSkin.setText("")
        self.LEditA_newSkin.setObjectName("LEditA_newSkin")
        self.horizontalLayout_12.addWidget(self.LEditA_newSkin)
        self.BtnA_newSkin = QtWidgets.QToolButton(self.groupBox_6)
        self.BtnA_newSkin.setObjectName("BtnA_newSkin")
        self.horizontalLayout_12.addWidget(self.BtnA_newSkin)
        self.BtnA_max_path_Pick = QtWidgets.QToolButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.BtnA_max_path_Pick.setFont(font)
        self.BtnA_max_path_Pick.setObjectName("BtnA_max_path_Pick")
        self.horizontalLayout_12.addWidget(self.BtnA_max_path_Pick)
        self.verticalLayout_13.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_7.setStyleSheet("QLineEdit{\n"
"background-color:rgb(90, 90, 90);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(40, 40, 40);\n"
"padding: 2px;\n"
"}")
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_13.setContentsMargins(9, -1, 9, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.LEditA_max_path = QtWidgets.QLineEdit(self.groupBox_7)
        self.LEditA_max_path.setStyleSheet("QLineEdit{\n"
"background-color:rgb(90, 90, 90);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(40, 40, 40);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"background-color:rgb(100, 100, 100);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(150, 150, 150);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:pressed {\n"
"background-color:rgb(110, 110, 110);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}")
        self.LEditA_max_path.setObjectName("LEditA_max_path")
        self.horizontalLayout_13.addWidget(self.LEditA_max_path)
        self.BtnA_max_path = QtWidgets.QToolButton(self.groupBox_7)
        self.BtnA_max_path.setObjectName("BtnA_max_path")
        self.horizontalLayout_13.addWidget(self.BtnA_max_path)
        self.BtnA_max_path_open = QtWidgets.QToolButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.BtnA_max_path_open.setFont(font)
        self.BtnA_max_path_open.setObjectName("BtnA_max_path_open")
        self.horizontalLayout_13.addWidget(self.BtnA_max_path_open)
        self.verticalLayout_13.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_14.setContentsMargins(9, -1, 9, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.LEditA_svae_path = QtWidgets.QLineEdit(self.groupBox_8)
        self.LEditA_svae_path.setStyleSheet("QLineEdit{\n"
"background-color:rgb(90, 90, 90);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(40, 40, 40);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"background-color:rgb(100, 100, 100);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(150, 150, 150);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:pressed {\n"
"background-color:rgb(110, 110, 110);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}")
        self.LEditA_svae_path.setObjectName("LEditA_svae_path")
        self.horizontalLayout_14.addWidget(self.LEditA_svae_path)
        self.BtnA_svae_path_auto = QtWidgets.QToolButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.BtnA_svae_path_auto.setFont(font)
        self.BtnA_svae_path_auto.setObjectName("BtnA_svae_path_auto")
        self.horizontalLayout_14.addWidget(self.BtnA_svae_path_auto)
        self.BtnA_svae_path = QtWidgets.QToolButton(self.groupBox_8)
        self.BtnA_svae_path.setObjectName("BtnA_svae_path")
        self.horizontalLayout_14.addWidget(self.BtnA_svae_path)
        self.BtnA_svae_path_open = QtWidgets.QToolButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.BtnA_svae_path_open.setFont(font)
        self.BtnA_svae_path_open.setObjectName("BtnA_svae_path_open")
        self.horizontalLayout_14.addWidget(self.BtnA_svae_path_open)
        self.verticalLayout_13.addWidget(self.groupBox_8)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setStyleSheet("QFrame#frame_6{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_15.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(18, 6, 18, 6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.CBoxA_List_subfolder = QtWidgets.QCheckBox(self.frame_6)
        self.CBoxA_List_subfolder.setFocusPolicy(QtCore.Qt.NoFocus)
        self.CBoxA_List_subfolder.setObjectName("CBoxA_List_subfolder")
        self.horizontalLayout_16.addWidget(self.CBoxA_List_subfolder)
        self.line = QtWidgets.QFrame(self.frame_6)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_16.addWidget(self.line)
        spacerItem8 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.BtnA_List_item_delete = QtWidgets.QToolButton(self.frame_6)
        self.BtnA_List_item_delete.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnA_List_item_delete.setObjectName("BtnA_List_item_delete")
        self.horizontalLayout_16.addWidget(self.BtnA_List_item_delete)
        self.BtnA_List_item_add = QtWidgets.QToolButton(self.frame_6)
        self.BtnA_List_item_add.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnA_List_item_add.setObjectName("BtnA_List_item_add")
        self.horizontalLayout_16.addWidget(self.BtnA_List_item_add)
        self.line_3 = QtWidgets.QFrame(self.frame_6)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_16.addWidget(self.line_3)
        self.BtnA_List_select_reverse = QtWidgets.QToolButton(self.frame_6)
        self.BtnA_List_select_reverse.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnA_List_select_reverse.setObjectName("BtnA_List_select_reverse")
        self.horizontalLayout_16.addWidget(self.BtnA_List_select_reverse)
        self.BtnA_List_select_all = QtWidgets.QToolButton(self.frame_6)
        self.BtnA_List_select_all.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnA_List_select_all.setObjectName("BtnA_List_select_all")
        self.horizontalLayout_16.addWidget(self.BtnA_List_select_all)
        self.line_2 = QtWidgets.QFrame(self.frame_6)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_16.addWidget(self.line_2)
        self.BtnA_RefreshList = QtWidgets.QToolButton(self.frame_6)
        self.BtnA_RefreshList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnA_RefreshList.setObjectName("BtnA_RefreshList")
        self.horizontalLayout_16.addWidget(self.BtnA_RefreshList)
        self.verticalLayout_15.addLayout(self.horizontalLayout_16)
        self.verticalLayout_7.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_17.setContentsMargins(9, 0, 9, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_5 = QtWidgets.QFrame(self.frame_8)
        self.frame_5.setStyleSheet("QFrame#frame_5{\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.treeWidgetA = QtWidgets.QTreeWidget(self.frame_5)
        self.treeWidgetA.setStyleSheet("QTreeWidget\n"
"{\n"
"background-color: rgb(80, 80, 80);\n"
"color:rgb(255, 255, 255);\n"
"border: 0px solid rgb(17, 17, 17);\n"
"border-radius: 6px;\n"
"}    \n"
"QTreeWidget::item {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left;\n"
"}\n"
"QTreeWidget::item:hover {\n"
"    background-color: rgb(52, 95, 251);\n"
"}\n"
"QTreeWidget::item:pressed {\n"
"    background-color: rgb(10, 50, 205);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"\n"
"QTreeWidget::item:selected {\n"
"    background-color:rgb(40, 105, 254);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"border: 0px ;\n"
"background-color:rgb(60, 60, 60);\n"
"width:6px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"background:rgb(225,225, 225);\n"
"min-height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"background: rgb(255, 0, 0);\n"
"       height: 0px;\n"
"     subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"#QScrollBar::sub-line:vertical {\n"
" background: rgb(0, 255, 17);\n"
"    height: 0 px;\n"
"     subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"    }\n"
"\n"
"QScrollBar:horizontal {\n"
"border: 0px ;\n"
"background-color:rgb(60, 60, 60);\n"
"\n"
"height:6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"background:rgb(225,225, 225);\n"
"min-width:0px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"background: rgb(255, 0, 0);\n"
"       width: 0px;\n"
"     subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"#QScrollBar::sub-line:horizontal{\n"
" background: rgb(0, 255, 17);\n"
"    width:0px;\n"
"     subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"    }")
        self.treeWidgetA.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeWidgetA.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeWidgetA.setAutoScrollMargin(15)
        self.treeWidgetA.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeWidgetA.setIndentation(0)
        self.treeWidgetA.setAnimated(False)
        self.treeWidgetA.setAllColumnsShowFocus(False)
        self.treeWidgetA.setWordWrap(False)
        self.treeWidgetA.setHeaderHidden(False)
        self.treeWidgetA.setObjectName("treeWidgetA")
        self.treeWidgetA.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetA)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetA)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetA)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetA)
        self.horizontalLayout_10.addWidget(self.treeWidgetA)
        self.verticalLayout_14.addLayout(self.horizontalLayout_10)
        self.verticalLayout_17.addWidget(self.frame_5)
        self.verticalLayout_7.addWidget(self.frame_8)
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setStyleSheet("QFrame#frame_10{\n"
"    background-color:rgb(65, 65, 65);\n"
"    border-radius:10px;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.groupBox_9 = QtWidgets.QGroupBox(self.frame_10)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem9 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem9)
        self.CBoxA_iskeyframe = QtWidgets.QCheckBox(self.groupBox_9)
        self.CBoxA_iskeyframe.setFocusPolicy(QtCore.Qt.NoFocus)
        self.CBoxA_iskeyframe.setObjectName("CBoxA_iskeyframe")
        self.horizontalLayout_20.addWidget(self.CBoxA_iskeyframe)
        self.CBoxA_bip_only = QtWidgets.QCheckBox(self.groupBox_9)
        self.CBoxA_bip_only.setFocusPolicy(QtCore.Qt.NoFocus)
        self.CBoxA_bip_only.setObjectName("CBoxA_bip_only")
        self.horizontalLayout_20.addWidget(self.CBoxA_bip_only)
        spacerItem10 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem10)
        self.horizontalLayout_19.addWidget(self.groupBox_9)
        self.verticalLayout_7.addWidget(self.frame_10)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.tabWidget_Anim.addTab(self.tab_3, "")
        self.verticalLayout_9.addWidget(self.tabWidget_Anim)
        self.verticalLayout_36.addLayout(self.verticalLayout_9)
        self.frame_7 = QtWidgets.QFrame(self.frame_anim)
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(9, 6, 9, 6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.progressBar = QtWidgets.QProgressBar(self.frame_7)
        self.progressBar.setStyleSheet("QProgressBar\n"
"{\n"
"background-color: rgb(120, 120, 120);\n"
"color:rgb(255, 255, 255);\n"
"min-height: 15px;\n"
"max-height: 15px;\n"
"border-radius: 6px;\n"
"}    \n"
"QProgressBar::chunk {\n"
"background-color: rgb(60, 200, 0);\n"
"    border-radius: 6px;\n"
"\n"
"}")
        self.progressBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_17.addWidget(self.progressBar)
        self.verticalLayout_16.addLayout(self.horizontalLayout_17)
        self.frame_message = QtWidgets.QFrame(self.frame_7)
        self.frame_message.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_message.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_message.setObjectName("frame_message")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_message)
        self.horizontalLayout_6.setContentsMargins(6, 6, 0, 6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(6, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(16)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.frame_message_success = QtWidgets.QFrame(self.frame_message)
        self.frame_message_success.setStyleSheet("QFrame#frame_message_success{\n"
"    background-color: rgba(80, 200, 80,100);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_message_success.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_message_success.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_message_success.setObjectName("frame_message_success")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_message_success)
        self.horizontalLayout_5.setContentsMargins(16, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_message_success = QtWidgets.QLabel(self.frame_message_success)
        self.label_message_success.setObjectName("label_message_success")
        self.horizontalLayout_5.addWidget(self.label_message_success)
        self.line_message_success = QtWidgets.QFrame(self.frame_message_success)
        self.line_message_success.setStyleSheet("Line {\n"
"\n"
"    color::rgba(255, 255, 255, 100);\n"
"\n"
"\n"
"\n"
"}")
        self.line_message_success.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_message_success.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_message_success.setObjectName("line_message_success")
        self.horizontalLayout_5.addWidget(self.line_message_success)
        self.Btn_message_success_close = QtWidgets.QToolButton(self.frame_message_success)
        self.Btn_message_success_close.setStyleSheet("QToolButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"\n"
"\n"
"}\n"
"QToolButton:hover {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"\n"
"}")
        self.Btn_message_success_close.setObjectName("Btn_message_success_close")
        self.horizontalLayout_5.addWidget(self.Btn_message_success_close)
        self.horizontalLayout_21.addWidget(self.frame_message_success)
        self.frame_message_error = QtWidgets.QFrame(self.frame_message)
        self.frame_message_error.setStyleSheet("QFrame#frame_message_error{\n"
"    background-color: rgba(200, 80, 80,100);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_message_error.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_message_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_message_error.setObjectName("frame_message_error")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_message_error)
        self.horizontalLayout_7.setContentsMargins(16, 0, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_message_error = QtWidgets.QLabel(self.frame_message_error)
        self.label_message_error.setObjectName("label_message_error")
        self.horizontalLayout_7.addWidget(self.label_message_error)
        self.Btn_message_error_log = QtWidgets.QToolButton(self.frame_message_error)
        self.Btn_message_error_log.setStyleSheet("QToolButton {\n"
"    background-color:rgba(40, 105, 254,100);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QToolButton:hover {\n"
"    background-color:rgba(14, 59, 229,100);\n"
"border-radius: 6px;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgba(1, 33, 154,100);\n"
"border-radius: 6px;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.Btn_message_error_log.setObjectName("Btn_message_error_log")
        self.horizontalLayout_7.addWidget(self.Btn_message_error_log)
        self.line_message_error = QtWidgets.QFrame(self.frame_message_error)
        self.line_message_error.setStyleSheet("Line {\n"
"\n"
"    color::rgba(255, 255, 255, 100);\n"
"\n"
"\n"
"\n"
"}")
        self.line_message_error.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_message_error.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_message_error.setObjectName("line_message_error")
        self.horizontalLayout_7.addWidget(self.line_message_error)
        self.Btn_message_error_close = QtWidgets.QToolButton(self.frame_message_error)
        self.Btn_message_error_close.setStyleSheet("QToolButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"\n"
"\n"
"}\n"
"QToolButton:hover {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"\n"
"}")
        self.Btn_message_error_close.setObjectName("Btn_message_error_close")
        self.horizontalLayout_7.addWidget(self.Btn_message_error_close)
        self.horizontalLayout_21.addWidget(self.frame_message_error)
        self.frame_message_tip = QtWidgets.QFrame(self.frame_message)
        self.frame_message_tip.setStyleSheet("QFrame#frame_message_tip{\n"
"    background-color: rgba(220, 220, 80,100);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_message_tip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_message_tip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_message_tip.setObjectName("frame_message_tip")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_message_tip)
        self.horizontalLayout_8.setContentsMargins(12, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_message_tip = QtWidgets.QLabel(self.frame_message_tip)
        self.label_message_tip.setObjectName("label_message_tip")
        self.horizontalLayout_8.addWidget(self.label_message_tip)
        self.line_message_tip = QtWidgets.QFrame(self.frame_message_tip)
        self.line_message_tip.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_message_tip.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_message_tip.setObjectName("line_message_tip")
        self.horizontalLayout_8.addWidget(self.line_message_tip)
        self.Btn_message_tip_close = QtWidgets.QToolButton(self.frame_message_tip)
        self.Btn_message_tip_close.setStyleSheet("QToolButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"\n"
"\n"
"}\n"
"QToolButton:hover {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"\n"
"}")
        self.Btn_message_tip_close.setObjectName("Btn_message_tip_close")
        self.horizontalLayout_8.addWidget(self.Btn_message_tip_close)
        self.horizontalLayout_21.addWidget(self.frame_message_tip)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_21)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.verticalLayout_16.addWidget(self.frame_message)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(9, 6, 0, 6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(120, 150, 254);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_19.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(120, 150, 254);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_19.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(120, 150, 254);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_19.addWidget(self.label_3)
        self.horizontalLayout_11.addLayout(self.verticalLayout_19)
        spacerItem12 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.BtnA_Apply = QtWidgets.QToolButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnA_Apply.sizePolicy().hasHeightForWidth())
        self.BtnA_Apply.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.BtnA_Apply.setFont(font)
        self.BtnA_Apply.setStyleSheet("QToolButton {\n"
"    background-color:rgb(40, 105, 254);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QToolButton:hover {\n"
"    background-color:rgb(14, 59, 229);\n"
"border-radius: 6px;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(1, 33, 154);\n"
"border-radius: 6px;\n"
"    border-style: inset;\n"
"}\n"
"\n"
"")
        self.BtnA_Apply.setObjectName("BtnA_Apply")
        self.horizontalLayout_11.addWidget(self.BtnA_Apply)
        self.verticalLayout_16.addLayout(self.horizontalLayout_11)
        self.verticalLayout_36.addWidget(self.frame_7)
        self.horizontalLayout_31.addWidget(self.frame_anim)
        self.frame_rig = QtWidgets.QFrame(self.dockWidgetContents)
        self.frame_rig.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_rig.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_rig.setObjectName("frame_rig")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_rig)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget_Rig = QtWidgets.QTabWidget(self.frame_rig)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_Rig.setFont(font)
        self.tabWidget_Rig.setObjectName("tabWidget_Rig")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem13 = QtWidgets.QSpacerItem(20, 657, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem13)
        self.tabWidget_Rig.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem14 = QtWidgets.QSpacerItem(20, 657, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem14)
        self.tabWidget_Rig.addTab(self.tab_4, "")
        self.verticalLayout_6.addWidget(self.tabWidget_Rig)
        self.horizontalLayout_31.addWidget(self.frame_rig)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.horizontalLayout_2.addWidget(self.dockWidget)
        mainWindow.setCentralWidget(self.centralwidget)
        self.dockWidget_2 = QtWidgets.QDockWidget(mainWindow)
        self.dockWidget_2.setFloating(False)
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetFloatable)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_11.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, 12, -1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label = QtWidgets.QLabel(self.dockWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_18.addWidget(self.label)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem15)
        self.toolButton_6 = QtWidgets.QToolButton(self.dockWidgetContents_2)
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout_18.addWidget(self.toolButton_6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_18)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setContentsMargins(0, 6, 12, 6)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.groupBox_10 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_25.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_25.setSpacing(6)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_22.setSpacing(6)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.frame_11 = QtWidgets.QFrame(self.groupBox_10)
        self.frame_11.setStyleSheet("QFrame#frame_11{\n"
"    background-color:rgb(65, 65, 65);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_11)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_23.addWidget(self.comboBox_2)
        self.toolButton_12 = QtWidgets.QToolButton(self.frame_11)
        self.toolButton_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_12.setObjectName("toolButton_12")
        self.horizontalLayout_23.addWidget(self.toolButton_12)
        self.horizontalLayout_22.addWidget(self.frame_11)
        self.verticalLayout_25.addLayout(self.horizontalLayout_22)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_9 = QtWidgets.QFrame(self.groupBox_10)
        self.frame_9.setStyleSheet("QFrame#frame_9{\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.listWidget_3 = QtWidgets.QListWidget(self.frame_9)
        self.listWidget_3.setStyleSheet("QListWidget#listWidget_3{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_18.addWidget(self.listWidget_3)
        self.verticalLayout_12.addWidget(self.frame_9)
        self.verticalLayout_25.addLayout(self.verticalLayout_12)
        self.verticalLayout_27.addWidget(self.groupBox_10)
        self.verticalLayout_11.addLayout(self.verticalLayout_27)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_2)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.dockWidget_3 = QtWidgets.QDockWidget(mainWindow)
        self.dockWidget_3.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetFloatable)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_20.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_20.setSpacing(6)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(-1, -1, 12, -1)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_25.addWidget(self.label_5)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem16)
        self.toolButton_13 = QtWidgets.QToolButton(self.dockWidgetContents_3)
        self.toolButton_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_13.setObjectName("toolButton_13")
        self.horizontalLayout_25.addWidget(self.toolButton_13)
        self.verticalLayout_20.addLayout(self.horizontalLayout_25)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(0, 0, 12, 6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_11 = QtWidgets.QGroupBox(self.dockWidgetContents_3)
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_26.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_13 = QtWidgets.QFrame(self.groupBox_11)
        self.frame_13.setStyleSheet("QFrame#frame_13{\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_22.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_22.setSpacing(6)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_13)
        self.textBrowser.setStyleSheet("QTextBrowser#textBrowser{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_23.addWidget(self.textBrowser)
        self.verticalLayout_22.addLayout(self.verticalLayout_23)
        self.verticalLayout_24.addWidget(self.frame_13)
        self.verticalLayout_26.addLayout(self.verticalLayout_24)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.frame_12 = QtWidgets.QFrame(self.groupBox_11)
        self.frame_12.setStyleSheet("QFrame#frame_12{\n"
"    background-color:rgb(65, 65, 65);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 6, 12, 6)
        self.horizontalLayout_15.setSpacing(4)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem17 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem17)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_15.addWidget(self.pushButton_4)
        self.verticalLayout_21.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_26.addWidget(self.frame_12)
        self.verticalLayout_26.addLayout(self.horizontalLayout_26)
        self.verticalLayout_10.addWidget(self.groupBox_11)
        self.verticalLayout_20.addLayout(self.verticalLayout_10)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_3)
        self.actionshow = QtWidgets.QAction(mainWindow)
        self.actionshow.setObjectName("actionshow")
        self.actionhide = QtWidgets.QAction(mainWindow)
        self.actionhide.setObjectName("actionhide")
        self.actiondoc = QtWidgets.QAction(mainWindow)
        self.actiondoc.setObjectName("actiondoc")
        self.actionsetting = QtWidgets.QAction(mainWindow)
        self.actionsetting.setObjectName("actionsetting")
        self.actionexport = QtWidgets.QAction(mainWindow)
        self.actionexport.setObjectName("actionexport")
        self.actionabout = QtWidgets.QAction(mainWindow)
        self.actionabout.setObjectName("actionabout")

        self.retranslateUi(mainWindow)
        self.tabWidget_Anim.setCurrentIndex(0)
        self.tabWidget_Rig.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "SN_Anim_Batch_Tool"))
        self.Menu_Right.headerItem().setText(0, _translate("mainWindow", "1"))
        __sortingEnabled = self.Menu_Right.isSortingEnabled()
        self.Menu_Right.setSortingEnabled(False)
        self.Menu_Right.topLevelItem(0).setText(0, _translate("mainWindow", " 动画"))
        self.Menu_Right.topLevelItem(1).setText(0, _translate("mainWindow", " 绑定"))
        self.Menu_Right.setSortingEnabled(__sortingEnabled)
        self.Btn_setting.setText(_translate("mainWindow", "⊛"))
        self.groupBox.setTitle(_translate("mainWindow", "max文件路径"))
        self.BtnB_max_path.setText(_translate("mainWindow", "..."))
        self.BtnB_max_path_open.setText(_translate("mainWindow", "↗"))
        self.groupBox_2.setTitle(_translate("mainWindow", "输出路径"))
        self.BtnB_svae_path_auto.setToolTip(_translate("mainWindow", "自动填写路径"))
        self.BtnB_svae_path_auto.setText(_translate("mainWindow", "↓"))
        self.BtnB_svae_path.setText(_translate("mainWindow", "..."))
        self.BtnB_svae_path_open.setText(_translate("mainWindow", "↗"))
        self.CBoxB_List_subfolder.setText(_translate("mainWindow", "列出子文件夹"))
        self.BtnB_List_item_delete.setText(_translate("mainWindow", "-"))
        self.BtnB_List_item_Add.setText(_translate("mainWindow", "+"))
        self.BtnB_List_select_reverse.setText(_translate("mainWindow", "反选"))
        self.BtnB_List_select_all.setText(_translate("mainWindow", "全选"))
        self.BtnB_RefreshList.setText(_translate("mainWindow", "刷新列表"))
        self.treeWidgetB.headerItem().setText(0, _translate("mainWindow", "序号"))
        self.treeWidgetB.headerItem().setText(1, _translate("mainWindow", "文件名"))
        self.treeWidgetB.headerItem().setText(2, _translate("mainWindow", "文件路径"))
        self.treeWidgetB.headerItem().setText(3, _translate("mainWindow", "修改时间"))
        __sortingEnabled = self.treeWidgetB.isSortingEnabled()
        self.treeWidgetB.setSortingEnabled(False)
        self.treeWidgetB.topLevelItem(0).setText(0, _translate("mainWindow", "New Item"))
        self.treeWidgetB.topLevelItem(1).setText(0, _translate("mainWindow", "New Item"))
        self.treeWidgetB.topLevelItem(2).setText(0, _translate("mainWindow", "New Item"))
        self.treeWidgetB.topLevelItem(3).setText(0, _translate("mainWindow", "New Item"))
        self.treeWidgetB.topLevelItem(4).setText(0, _translate("mainWindow", "New Item"))
        self.treeWidgetB.setSortingEnabled(__sortingEnabled)
        self.groupBox_12.setTitle(_translate("mainWindow", "FBX输出设置"))
        self.radioBtnB_fbx_sn.setText(_translate("mainWindow", "SN项目标准输出"))
        self.radioBtnB_fbx_custom.setText(_translate("mainWindow", "自定义输出"))
        self.CBoxB_fbx_sn_export_ani_set.setText(_translate("mainWindow", "输出Export_ani选择集"))
        self.CBoxB_fbx_sn_root_zero.setText(_translate("mainWindow", "root归零"))
        self.groupBox_15.setTitle(_translate("mainWindow", "导出对象"))
        self.radioBtnB_fbx_custom_set.setText(_translate("mainWindow", "自定义选择集"))
        self.radioBtnB_fbx_custom_objs.setText(_translate("mainWindow", "自定义对象"))
        self.BtnB_fbx_custom_objs_pick.setText(_translate("mainWindow", "指定当前选择物体"))
        self.CBoxB_fbx_custom_backanimation.setText(_translate("mainWindow", "烘培动画"))
        self.CBoxB_fbx_custom_BakeResampleAnimation.setText(_translate("mainWindow", "全部重采样"))
        self.CBoxB_fbx_custom_cvfix.setText(_translate("mainWindow", "曲线修正"))
        self.tabWidget_Anim.setTabText(self.tabWidget_Anim.indexOf(self.tab), _translate("mainWindow", "批量导出FBX"))
        self.groupBox_6.setTitle(_translate("mainWindow", "新的skin文件"))
        self.BtnA_newSkin.setToolTip(_translate("mainWindow", "指定max文件"))
        self.BtnA_newSkin.setText(_translate("mainWindow", "..."))
        self.BtnA_max_path_Pick.setToolTip(_translate("mainWindow", "指定当前文件"))
        self.BtnA_max_path_Pick.setText(_translate("mainWindow", "↙"))
        self.groupBox_7.setTitle(_translate("mainWindow", "max文件路径"))
        self.BtnA_max_path.setToolTip(_translate("mainWindow", "指定路径"))
        self.BtnA_max_path.setText(_translate("mainWindow", "..."))
        self.BtnA_max_path_open.setToolTip(_translate("mainWindow", "在资源管理器打开"))
        self.BtnA_max_path_open.setText(_translate("mainWindow", "↗"))
        self.groupBox_8.setTitle(_translate("mainWindow", "保存路径"))
        self.BtnA_svae_path_auto.setToolTip(_translate("mainWindow", "自动填写路径"))
        self.BtnA_svae_path_auto.setText(_translate("mainWindow", "↓"))
        self.BtnA_svae_path.setToolTip(_translate("mainWindow", "指定路径"))
        self.BtnA_svae_path.setText(_translate("mainWindow", "..."))
        self.BtnA_svae_path_open.setToolTip(_translate("mainWindow", "在资源管理器打开"))
        self.BtnA_svae_path_open.setText(_translate("mainWindow", "↗"))
        self.CBoxA_List_subfolder.setText(_translate("mainWindow", "列出子文件夹"))
        self.BtnA_List_item_delete.setText(_translate("mainWindow", "-"))
        self.BtnA_List_item_add.setText(_translate("mainWindow", "+"))
        self.BtnA_List_select_reverse.setText(_translate("mainWindow", "反选"))
        self.BtnA_List_select_all.setText(_translate("mainWindow", "全选"))
        self.BtnA_RefreshList.setText(_translate("mainWindow", "刷新列表"))
        self.treeWidgetA.headerItem().setText(0, _translate("mainWindow", "序号"))
        self.treeWidgetA.headerItem().setText(1, _translate("mainWindow", "文件名"))
        self.treeWidgetA.headerItem().setText(2, _translate("mainWindow", "文件路径"))
        self.treeWidgetA.headerItem().setText(3, _translate("mainWindow", "修改时间"))
        __sortingEnabled = self.treeWidgetA.isSortingEnabled()
        self.treeWidgetA.setSortingEnabled(False)
        self.treeWidgetA.topLevelItem(0).setText(0, _translate("mainWindow", "0"))
        self.treeWidgetA.topLevelItem(1).setText(0, _translate("mainWindow", "5"))
        self.treeWidgetA.topLevelItem(1).child(0).setText(0, _translate("mainWindow", "New Subitem"))
        self.treeWidgetA.topLevelItem(1).child(0).child(0).setText(0, _translate("mainWindow", "New Subitem"))
        self.treeWidgetA.topLevelItem(1).child(0).child(0).child(0).setText(0, _translate("mainWindow", "New Subitem"))
        self.treeWidgetA.topLevelItem(2).setText(0, _translate("mainWindow", "6"))
        self.treeWidgetA.topLevelItem(3).setText(0, _translate("mainWindow", "7"))
        self.treeWidgetA.setSortingEnabled(__sortingEnabled)
        self.groupBox_9.setTitle(_translate("mainWindow", "输出设置"))
        self.CBoxA_iskeyframe.setText(_translate("mainWindow", "bone关键帧"))
        self.CBoxA_bip_only.setText(_translate("mainWindow", "只替换bip动画"))
        self.tabWidget_Anim.setTabText(self.tabWidget_Anim.indexOf(self.tab_3), _translate("mainWindow", "批量替换模型"))
        self.progressBar.setFormat(_translate("mainWindow", "%p%"))
        self.label_message_success.setText(_translate("mainWindow", "处理成功！"))
        self.Btn_message_success_close.setText(_translate("mainWindow", "X"))
        self.label_message_error.setText(_translate("mainWindow", "出错了 淦"))
        self.Btn_message_error_log.setText(_translate("mainWindow", "查看出错日志"))
        self.Btn_message_error_close.setText(_translate("mainWindow", "X"))
        self.label_message_tip.setText(_translate("mainWindow", "请检查"))
        self.Btn_message_tip_close.setText(_translate("mainWindow", "X"))
        self.label_2.setText(_translate("mainWindow", "内部版本请勿外泄"))
        self.label_4.setText(_translate("mainWindow", "光子工作室-SN项目-美术组"))
        self.label_3.setText(_translate("mainWindow", "@2023"))
        self.BtnA_Apply.setText(_translate("mainWindow", "    应用    "))
        self.tabWidget_Rig.setTabText(self.tabWidget_Rig.indexOf(self.tab_2), _translate("mainWindow", "temp"))
        self.tabWidget_Rig.setTabText(self.tabWidget_Rig.indexOf(self.tab_4), _translate("mainWindow", "temp2"))
        self.label.setText(_translate("mainWindow", "输出日志"))
        self.toolButton_6.setText(_translate("mainWindow", "X"))
        self.toolButton_12.setText(_translate("mainWindow", "刷新"))
        self.label_5.setText(_translate("mainWindow", "处理进度"))
        self.toolButton_13.setText(_translate("mainWindow", "X"))
        self.textBrowser.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">test</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">tesetttt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">testttttttt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">test</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">tesetttt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">testttttttt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">test</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">tesetttt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">testttttttt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">test</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">tesetttt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">testttttttt</p></body></html>"))
        self.pushButton_4.setText(_translate("mainWindow", "清空列表"))
        self.actionshow.setText(_translate("mainWindow", "显示日志窗口"))
        self.actionhide.setText(_translate("mainWindow", "隐藏日志窗口"))
        self.actiondoc.setText(_translate("mainWindow", "帮助文档"))
        self.actionsetting.setText(_translate("mainWindow", "设置"))
        self.actionexport.setText(_translate("mainWindow", "输出目录"))
        self.actionabout.setText(_translate("mainWindow", "关于"))
