# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bath_tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(985, 928)
        mainWindow.setStyleSheet("QMainWindow#MainWindow\n"
"{\n"
"background-color:rgb(200, 200, 200);\n"
"}    \n"
"")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dockWidget = QtWidgets.QDockWidget(self.centralwidget)
        self.dockWidget.setStyleSheet("QScrollBar:vertical {\n"
"border: 0px ;\n"
"background-color:rgb(60, 60, 60);\n"
"width:6px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"background:rgb(225,225, 225);\n"
"min-height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"background: rgb(255, 0, 0);\n"
"       height: 0px;\n"
"     subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"#QScrollBar::sub-line:vertical {\n"
" background: rgb(0, 255, 17);\n"
"    height: 0 px;\n"
"     subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"    }\n"
"\n"
"QScrollBar:horizontal {\n"
"border: 0px ;\n"
"background-color:rgb(60, 60, 60);\n"
"\n"
"height:6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"background:rgb(225,225, 225);\n"
"min-width:0px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"background: rgb(255, 0, 0);\n"
"       width: 0px;\n"
"     subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"#QScrollBar::sub-line:horizontal{\n"
" background: rgb(0, 255, 17);\n"
"    width:0px;\n"
"     subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"    }")
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetFloatable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget_2.setUsesScrollButtons(False)
        self.tabWidget_2.setDocumentMode(False)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setMovable(False)
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setStyleSheet("QFrame#frame_14{\n"
"    background-color:rgb(65, 65, 65);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.groupBox = QtWidgets.QGroupBox(self.frame_14)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"background-color:rgb(90, 90, 90);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(40, 40, 40);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"background-color:rgb(100, 100, 100);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(150, 150, 150);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:pressed {\n"
"background-color:rgb(110, 110, 110);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:nameEdit {\n"
"background-color:rgb(225, 225, 225);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:read-only{\n"
"background-color:rgb(225, 225, 225);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.toolButton = QtWidgets.QToolButton(self.groupBox)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.toolButton_17 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_17.setObjectName("toolButton_17")
        self.horizontalLayout.addWidget(self.toolButton_17)
        self.verticalLayout_29.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_14)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"background-color:rgb(90, 90, 90);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(40, 40, 40);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"background-color:rgb(100, 100, 100);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(150, 150, 150);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:pressed {\n"
"background-color:rgb(110, 110, 110);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:nameEdit {\n"
"background-color:rgb(225, 225, 225);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:read-only{\n"
"background-color:rgb(225, 225, 225);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_3.addWidget(self.toolButton_2)
        self.toolButton_16 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_16.setObjectName("toolButton_16")
        self.horizontalLayout_3.addWidget(self.toolButton_16)
        self.verticalLayout_29.addWidget(self.groupBox_2)
        self.verticalLayout_2.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(18, 6, 18, 6)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.checkBox = QtWidgets.QCheckBox(self.frame_15)
        self.checkBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_24.addWidget(self.checkBox)
        self.line_4 = QtWidgets.QFrame(self.frame_15)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_24.addWidget(self.line_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem)
        self.toolButton_21 = QtWidgets.QToolButton(self.frame_15)
        self.toolButton_21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_21.setObjectName("toolButton_21")
        self.horizontalLayout_24.addWidget(self.toolButton_21)
        self.toolButton_22 = QtWidgets.QToolButton(self.frame_15)
        self.toolButton_22.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_22.setObjectName("toolButton_22")
        self.horizontalLayout_24.addWidget(self.toolButton_22)
        self.line_5 = QtWidgets.QFrame(self.frame_15)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_24.addWidget(self.line_5)
        self.toolButton_20 = QtWidgets.QToolButton(self.frame_15)
        self.toolButton_20.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_20.setObjectName("toolButton_20")
        self.horizontalLayout_24.addWidget(self.toolButton_20)
        self.toolButton_19 = QtWidgets.QToolButton(self.frame_15)
        self.toolButton_19.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_19.setObjectName("toolButton_19")
        self.horizontalLayout_24.addWidget(self.toolButton_19)
        self.line_6 = QtWidgets.QFrame(self.frame_15)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_24.addWidget(self.line_6)
        self.toolButton_18 = QtWidgets.QToolButton(self.frame_15)
        self.toolButton_18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_18.setObjectName("toolButton_18")
        self.horizontalLayout_24.addWidget(self.toolButton_18)
        self.verticalLayout_30.addLayout(self.horizontalLayout_24)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame_18 = QtWidgets.QFrame(self.frame)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_29.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.frame_17 = QtWidgets.QFrame(self.frame_18)
        self.frame_17.setStyleSheet("QFrame#frame_17{\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.treeWidget = QtWidgets.QTreeWidget(self.frame_17)
        self.treeWidget.setStyleSheet("QTreeWidget\n"
"{\n"
"background-color: rgb(80, 80, 80);\n"
"color:rgb(255, 255, 255);\n"
"border: 0px solid rgb(17, 17, 17);\n"
"border-radius: 6px;\n"
"}    \n"
"QTreeWidget::item {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left;\n"
"}\n"
"QTreeWidget::item:hover {\n"
"    background-color: rgb(52, 95, 251);\n"
"}\n"
"QTreeWidget::item:pressed {\n"
"    background-color: rgb(10, 50, 205);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"\n"
"QTreeWidget::item:selected {\n"
"    background-color:rgb(40, 105, 254);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"border: 0px ;\n"
"background-color:rgb(60, 60, 60);\n"
"width:6px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"background:rgb(225,225, 225);\n"
"min-height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"background: rgb(255, 0, 0);\n"
"       height: 0px;\n"
"     subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"#QScrollBar::sub-line:vertical {\n"
" background: rgb(0, 255, 17);\n"
"    height: 0 px;\n"
"     subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"    }\n"
"\n"
"QScrollBar:horizontal {\n"
"border: 0px ;\n"
"background-color:rgb(60, 60, 60);\n"
"\n"
"height:6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"background:rgb(225,225, 225);\n"
"min-width:0px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"background: rgb(255, 0, 0);\n"
"       width: 0px;\n"
"     subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"#QScrollBar::sub-line:horizontal{\n"
" background: rgb(0, 255, 17);\n"
"    width:0px;\n"
"     subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"    }\n"
"")
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.horizontalLayout_30.addWidget(self.treeWidget)
        self.verticalLayout_32.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_29.addWidget(self.frame_17)
        self.verticalLayout_2.addWidget(self.frame_18)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(9, -1, 9, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.frame_16 = QtWidgets.QFrame(self.frame)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.groupBox_12 = QtWidgets.QGroupBox(self.frame_16)
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.toolBox = QtWidgets.QToolBox(self.groupBox_12)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 577, 161))
        self.page.setObjectName("page")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 577, 161))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.verticalLayout_31.addWidget(self.toolBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(9, 6, 9, 6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_4.addWidget(self.checkBox_4)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_4.addWidget(self.checkBox_3)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_4.addWidget(self.checkBox_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_31.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_28.addLayout(self.verticalLayout_31)
        self.horizontalLayout_27.addWidget(self.groupBox_12)
        self.verticalLayout_2.addWidget(self.frame_16)
        self.verticalLayout_3.addWidget(self.frame)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.tab_3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setStyleSheet("QFrame#frame_4{\n"
"    background-color:rgb(65, 65, 65);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_13.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_12.setContentsMargins(9, -1, 9, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.LEdit_newSkin = QtWidgets.QLineEdit(self.groupBox_6)
        self.LEdit_newSkin.setStyleSheet("QLineEdit{\n"
"background-color:rgb(90, 90, 90);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(40, 40, 40);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"background-color:rgb(100, 100, 100);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(150, 150, 150);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:pressed {\n"
"background-color:rgb(110, 110, 110);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:nameEdit {\n"
"background-color:rgb(225, 225, 225);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:read-only{\n"
"background-color:rgb(225, 225, 225);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}")
        self.LEdit_newSkin.setText("")
        self.LEdit_newSkin.setObjectName("LEdit_newSkin")
        self.horizontalLayout_12.addWidget(self.LEdit_newSkin)
        self.BtnA_newSkin = QtWidgets.QToolButton(self.groupBox_6)
        self.BtnA_newSkin.setObjectName("BtnA_newSkin")
        self.horizontalLayout_12.addWidget(self.BtnA_newSkin)
        self.toolButton_7 = QtWidgets.QToolButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_7.setFont(font)
        self.toolButton_7.setObjectName("toolButton_7")
        self.horizontalLayout_12.addWidget(self.toolButton_7)
        self.verticalLayout_13.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_7.setStyleSheet("QLineEdit{\n"
"background-color:rgb(90, 90, 90);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(40, 40, 40);\n"
"padding: 2px;\n"
"}")
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_13.setContentsMargins(9, -1, 9, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.LEdit_max_path = QtWidgets.QLineEdit(self.groupBox_7)
        self.LEdit_max_path.setStyleSheet("QLineEdit{\n"
"background-color:rgb(90, 90, 90);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(40, 40, 40);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"background-color:rgb(100, 100, 100);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(150, 150, 150);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:pressed {\n"
"background-color:rgb(110, 110, 110);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}")
        self.LEdit_max_path.setObjectName("LEdit_max_path")
        self.horizontalLayout_13.addWidget(self.LEdit_max_path)
        self.BtnA_max_path = QtWidgets.QToolButton(self.groupBox_7)
        self.BtnA_max_path.setObjectName("BtnA_max_path")
        self.horizontalLayout_13.addWidget(self.BtnA_max_path)
        self.toolButton_14 = QtWidgets.QToolButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_14.setFont(font)
        self.toolButton_14.setObjectName("toolButton_14")
        self.horizontalLayout_13.addWidget(self.toolButton_14)
        self.verticalLayout_13.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_14.setContentsMargins(9, -1, 9, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.LEdit_svae_path = QtWidgets.QLineEdit(self.groupBox_8)
        self.LEdit_svae_path.setStyleSheet("QLineEdit{\n"
"background-color:rgb(90, 90, 90);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(40, 40, 40);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"background-color:rgb(100, 100, 100);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(150, 150, 150);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:pressed {\n"
"background-color:rgb(110, 110, 110);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}")
        self.LEdit_svae_path.setObjectName("LEdit_svae_path")
        self.horizontalLayout_14.addWidget(self.LEdit_svae_path)
        self.BtnA_svae_path = QtWidgets.QToolButton(self.groupBox_8)
        self.BtnA_svae_path.setObjectName("BtnA_svae_path")
        self.horizontalLayout_14.addWidget(self.BtnA_svae_path)
        self.toolButton_15 = QtWidgets.QToolButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_15.setFont(font)
        self.toolButton_15.setObjectName("toolButton_15")
        self.horizontalLayout_14.addWidget(self.toolButton_15)
        self.verticalLayout_13.addWidget(self.groupBox_8)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setStyleSheet("QFrame#frame_6{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_15.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(18, 6, 18, 6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.CBoxA_sub_file = QtWidgets.QCheckBox(self.frame_6)
        self.CBoxA_sub_file.setFocusPolicy(QtCore.Qt.NoFocus)
        self.CBoxA_sub_file.setObjectName("CBoxA_sub_file")
        self.horizontalLayout_16.addWidget(self.CBoxA_sub_file)
        self.line = QtWidgets.QFrame(self.frame_6)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_16.addWidget(self.line)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.toolButton_10 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_10.setObjectName("toolButton_10")
        self.horizontalLayout_16.addWidget(self.toolButton_10)
        self.toolButton_11 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_11.setObjectName("toolButton_11")
        self.horizontalLayout_16.addWidget(self.toolButton_11)
        self.line_3 = QtWidgets.QFrame(self.frame_6)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_16.addWidget(self.line_3)
        self.toolButton_8 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_8.setObjectName("toolButton_8")
        self.horizontalLayout_16.addWidget(self.toolButton_8)
        self.toolButton_9 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_9.setObjectName("toolButton_9")
        self.horizontalLayout_16.addWidget(self.toolButton_9)
        self.line_2 = QtWidgets.QFrame(self.frame_6)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_16.addWidget(self.line_2)
        self.BtnA_RefreshList = QtWidgets.QToolButton(self.frame_6)
        self.BtnA_RefreshList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnA_RefreshList.setObjectName("BtnA_RefreshList")
        self.horizontalLayout_16.addWidget(self.BtnA_RefreshList)
        self.verticalLayout_15.addLayout(self.horizontalLayout_16)
        self.verticalLayout_7.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_17.setContentsMargins(9, 0, 9, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_5 = QtWidgets.QFrame(self.frame_8)
        self.frame_5.setStyleSheet("QFrame#frame_5{\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.treeWidgetA = QtWidgets.QTreeWidget(self.frame_5)
        self.treeWidgetA.setStyleSheet("QTreeWidget\n"
"{\n"
"background-color: rgb(80, 80, 80);\n"
"color:rgb(255, 255, 255);\n"
"border: 0px solid rgb(17, 17, 17);\n"
"border-radius: 6px;\n"
"}    \n"
"QTreeWidget::item {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left;\n"
"}\n"
"QTreeWidget::item:hover {\n"
"    background-color: rgb(52, 95, 251);\n"
"}\n"
"QTreeWidget::item:pressed {\n"
"    background-color: rgb(10, 50, 205);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"\n"
"QTreeWidget::item:selected {\n"
"    background-color:rgb(40, 105, 254);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"border: 0px ;\n"
"background-color:rgb(60, 60, 60);\n"
"width:6px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"background:rgb(225,225, 225);\n"
"min-height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"background: rgb(255, 0, 0);\n"
"       height: 0px;\n"
"     subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"#QScrollBar::sub-line:vertical {\n"
" background: rgb(0, 255, 17);\n"
"    height: 0 px;\n"
"     subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"    }\n"
"\n"
"QScrollBar:horizontal {\n"
"border: 0px ;\n"
"background-color:rgb(60, 60, 60);\n"
"\n"
"height:6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"background:rgb(225,225, 225);\n"
"min-width:0px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"background: rgb(255, 0, 0);\n"
"       width: 0px;\n"
"     subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"#QScrollBar::sub-line:horizontal{\n"
" background: rgb(0, 255, 17);\n"
"    width:0px;\n"
"     subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"    }")
        self.treeWidgetA.setAutoScrollMargin(15)
        self.treeWidgetA.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeWidgetA.setIndentation(15)
        self.treeWidgetA.setAnimated(False)
        self.treeWidgetA.setAllColumnsShowFocus(False)
        self.treeWidgetA.setWordWrap(False)
        self.treeWidgetA.setHeaderHidden(False)
        self.treeWidgetA.setObjectName("treeWidgetA")
        self.treeWidgetA.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetA)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetA)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetA)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetA)
        self.horizontalLayout_10.addWidget(self.treeWidgetA)
        self.verticalLayout_14.addLayout(self.horizontalLayout_10)
        self.verticalLayout_17.addWidget(self.frame_5)
        self.verticalLayout_7.addWidget(self.frame_8)
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setStyleSheet("QFrame#frame_10{\n"
"    background-color:rgb(65, 65, 65);\n"
"    border-radius:10px;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.groupBox_9 = QtWidgets.QGroupBox(self.frame_10)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem4)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_20.addWidget(self.checkBox_2)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_20.addWidget(self.checkBox_5)
        spacerItem5 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem5)
        self.horizontalLayout_19.addWidget(self.groupBox_9)
        self.verticalLayout_7.addWidget(self.frame_10)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(9, 6, 9, 6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.progressBar = QtWidgets.QProgressBar(self.frame_3)
        self.progressBar.setStyleSheet("QProgressBar\n"
"{\n"
"background-color: rgb(120, 120, 120);\n"
"color:rgb(255, 255, 255);\n"
"min-height: 15px;\n"
"max-height: 15px;\n"
"border-radius: 6px;\n"
"}    \n"
"QProgressBar::chunk {\n"
"background-color: rgb(60, 200, 0);\n"
"    border-radius: 6px;\n"
"\n"
"}")
        self.progressBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_17.addWidget(self.progressBar)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(12, 6, 12, 6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem6)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_21.addWidget(self.label_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_7.addWidget(self.lineEdit_3)
        self.toolButton_3 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_7.addWidget(self.toolButton_3)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_8.addWidget(self.lineEdit_4)
        self.toolButton_4 = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_8.addWidget(self.toolButton_4)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_9.addWidget(self.lineEdit_5)
        self.toolButton_5 = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout_9.addWidget(self.toolButton_5)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(9, 6, 9, 6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.frame_2)
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.treeWidget_2.headerItem().setText(0, "1")
        self.horizontalLayout_5.addWidget(self.treeWidget_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(9, 6, 9, 6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_9.addWidget(self.tabWidget)
        self.verticalLayout_28.addLayout(self.verticalLayout_9)
        self.frame_7 = QtWidgets.QFrame(self.tab_4)
        self.frame_7.setStyleSheet("\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(9, 6, 0, 6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(120, 150, 254);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_19.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(120, 150, 254);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_19.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(120, 150, 254);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_19.addWidget(self.label_3)
        self.horizontalLayout_11.addLayout(self.verticalLayout_19)
        spacerItem8 = QtWidgets.QSpacerItem(15, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.BtnA_Apply = QtWidgets.QPushButton(self.frame_7)
        self.BtnA_Apply.setMinimumSize(QtCore.QSize(160, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnA_Apply.setFont(font)
        self.BtnA_Apply.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BtnA_Apply.setStyleSheet("QPushButton {\n"
"    background-color:rgb(40, 105, 254);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(14, 59, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(1, 33, 154);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"")
        self.BtnA_Apply.setObjectName("BtnA_Apply")
        self.horizontalLayout_11.addWidget(self.BtnA_Apply)
        self.verticalLayout_16.addLayout(self.horizontalLayout_11)
        self.verticalLayout_28.addWidget(self.frame_7)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget_2)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.horizontalLayout_2.addWidget(self.dockWidget)
        mainWindow.setCentralWidget(self.centralwidget)
        self.dockWidget_2 = QtWidgets.QDockWidget(mainWindow)
        self.dockWidget_2.setFloating(False)
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetFloatable)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_11.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, 12, -1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label = QtWidgets.QLabel(self.dockWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_18.addWidget(self.label)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem9)
        self.toolButton_6 = QtWidgets.QToolButton(self.dockWidgetContents_2)
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout_18.addWidget(self.toolButton_6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_18)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setContentsMargins(0, 6, 12, 6)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.groupBox_10 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_25.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_25.setSpacing(6)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_22.setSpacing(6)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.frame_11 = QtWidgets.QFrame(self.groupBox_10)
        self.frame_11.setStyleSheet("QFrame#frame_11{\n"
"    background-color:rgb(65, 65, 65);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_11)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_23.addWidget(self.comboBox_2)
        self.toolButton_12 = QtWidgets.QToolButton(self.frame_11)
        self.toolButton_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_12.setObjectName("toolButton_12")
        self.horizontalLayout_23.addWidget(self.toolButton_12)
        self.horizontalLayout_22.addWidget(self.frame_11)
        self.verticalLayout_25.addLayout(self.horizontalLayout_22)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_9 = QtWidgets.QFrame(self.groupBox_10)
        self.frame_9.setStyleSheet("QFrame#frame_9{\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.listWidget_3 = QtWidgets.QListWidget(self.frame_9)
        self.listWidget_3.setStyleSheet("QListWidget#listWidget_3{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_18.addWidget(self.listWidget_3)
        self.verticalLayout_12.addWidget(self.frame_9)
        self.verticalLayout_25.addLayout(self.verticalLayout_12)
        self.verticalLayout_27.addWidget(self.groupBox_10)
        self.verticalLayout_11.addLayout(self.verticalLayout_27)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_2)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 985, 18))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        mainWindow.setMenuBar(self.menuBar)
        self.dockWidget_3 = QtWidgets.QDockWidget(mainWindow)
        self.dockWidget_3.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetFloatable)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_20.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_20.setSpacing(6)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(-1, -1, 12, -1)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_25.addWidget(self.label_5)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem10)
        self.toolButton_13 = QtWidgets.QToolButton(self.dockWidgetContents_3)
        self.toolButton_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_13.setObjectName("toolButton_13")
        self.horizontalLayout_25.addWidget(self.toolButton_13)
        self.verticalLayout_20.addLayout(self.horizontalLayout_25)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(0, 0, 12, 6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_11 = QtWidgets.QGroupBox(self.dockWidgetContents_3)
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_26.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_13 = QtWidgets.QFrame(self.groupBox_11)
        self.frame_13.setStyleSheet("QFrame#frame_13{\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_22.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_22.setSpacing(6)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_13)
        self.textBrowser.setStyleSheet("QTextBrowser#textBrowser{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_23.addWidget(self.textBrowser)
        self.verticalLayout_22.addLayout(self.verticalLayout_23)
        self.verticalLayout_24.addWidget(self.frame_13)
        self.verticalLayout_26.addLayout(self.verticalLayout_24)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.frame_12 = QtWidgets.QFrame(self.groupBox_11)
        self.frame_12.setStyleSheet("QFrame#frame_12{\n"
"    background-color:rgb(65, 65, 65);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 6, 12, 6)
        self.horizontalLayout_15.setSpacing(4)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem11 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem11)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_15.addWidget(self.pushButton_4)
        self.verticalLayout_21.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_26.addWidget(self.frame_12)
        self.verticalLayout_26.addLayout(self.horizontalLayout_26)
        self.verticalLayout_10.addWidget(self.groupBox_11)
        self.verticalLayout_20.addLayout(self.verticalLayout_10)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_3)
        self.actionshow = QtWidgets.QAction(mainWindow)
        self.actionshow.setObjectName("actionshow")
        self.actionhide = QtWidgets.QAction(mainWindow)
        self.actionhide.setObjectName("actionhide")
        self.actiondoc = QtWidgets.QAction(mainWindow)
        self.actiondoc.setObjectName("actiondoc")
        self.actionsetting = QtWidgets.QAction(mainWindow)
        self.actionsetting.setObjectName("actionsetting")
        self.actionexport = QtWidgets.QAction(mainWindow)
        self.actionexport.setObjectName("actionexport")
        self.menu.addAction(self.actionsetting)
        self.menu.addAction(self.actionexport)
        self.menu_2.addAction(self.actionshow)
        self.menu_2.addAction(self.actionhide)
        self.menu_3.addAction(self.actiondoc)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "SN_Anim_Batch_Tool"))
        self.tab_4.setToolTip(_translate("mainWindow", "动画"))
        self.groupBox.setTitle(_translate("mainWindow", "max文件路径"))
        self.toolButton.setText(_translate("mainWindow", "..."))
        self.toolButton_17.setText(_translate("mainWindow", "↙"))
        self.groupBox_2.setTitle(_translate("mainWindow", "输出路径"))
        self.toolButton_2.setText(_translate("mainWindow", "..."))
        self.toolButton_16.setText(_translate("mainWindow", "↗"))
        self.checkBox.setText(_translate("mainWindow", "列出子文件夹"))
        self.toolButton_21.setText(_translate("mainWindow", "-"))
        self.toolButton_22.setText(_translate("mainWindow", "+"))
        self.toolButton_20.setText(_translate("mainWindow", "全选"))
        self.toolButton_19.setText(_translate("mainWindow", "反选"))
        self.toolButton_18.setText(_translate("mainWindow", "刷新列表"))
        self.treeWidget.headerItem().setText(0, _translate("mainWindow", "序号"))
        self.treeWidget.headerItem().setText(1, _translate("mainWindow", "文件名"))
        self.treeWidget.headerItem().setText(2, _translate("mainWindow", "文件路径"))
        self.treeWidget.headerItem().setText(3, _translate("mainWindow", "修改时间"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("mainWindow", "New Item"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("mainWindow", "New Item"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("mainWindow", "New Item"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("mainWindow", "New Item"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("mainWindow", "New Item"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_12.setTitle(_translate("mainWindow", "FBX输出设置"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("mainWindow", "Page 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("mainWindow", "Page 2"))
        self.checkBox_4.setText(_translate("mainWindow", "烘培动画"))
        self.checkBox_3.setText(_translate("mainWindow", "全部重采样"))
        self.checkBox_6.setText(_translate("mainWindow", "曲线修正"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "批量导出FBX"))
        self.groupBox_6.setTitle(_translate("mainWindow", "新的skin文件"))
        self.BtnA_newSkin.setToolTip(_translate("mainWindow", "指定max文件"))
        self.BtnA_newSkin.setText(_translate("mainWindow", "..."))
        self.toolButton_7.setToolTip(_translate("mainWindow", "指定当前文件"))
        self.toolButton_7.setText(_translate("mainWindow", "↙"))
        self.groupBox_7.setTitle(_translate("mainWindow", "max文件路径"))
        self.BtnA_max_path.setToolTip(_translate("mainWindow", "指定路径"))
        self.BtnA_max_path.setText(_translate("mainWindow", "..."))
        self.toolButton_14.setToolTip(_translate("mainWindow", "在资源管理器打开"))
        self.toolButton_14.setText(_translate("mainWindow", "↗"))
        self.groupBox_8.setTitle(_translate("mainWindow", "保存路径"))
        self.BtnA_svae_path.setToolTip(_translate("mainWindow", "指定路径"))
        self.BtnA_svae_path.setText(_translate("mainWindow", "..."))
        self.toolButton_15.setToolTip(_translate("mainWindow", "在资源管理器打开"))
        self.toolButton_15.setText(_translate("mainWindow", "↗"))
        self.CBoxA_sub_file.setText(_translate("mainWindow", "列出子文件夹"))
        self.toolButton_10.setText(_translate("mainWindow", "-"))
        self.toolButton_11.setText(_translate("mainWindow", "+"))
        self.toolButton_8.setText(_translate("mainWindow", "全选"))
        self.toolButton_9.setText(_translate("mainWindow", "反选"))
        self.BtnA_RefreshList.setText(_translate("mainWindow", "刷新列表"))
        self.treeWidgetA.headerItem().setText(0, _translate("mainWindow", "序号"))
        self.treeWidgetA.headerItem().setText(1, _translate("mainWindow", "文件名"))
        self.treeWidgetA.headerItem().setText(2, _translate("mainWindow", "文件路径"))
        self.treeWidgetA.headerItem().setText(3, _translate("mainWindow", "修改时间"))
        __sortingEnabled = self.treeWidgetA.isSortingEnabled()
        self.treeWidgetA.setSortingEnabled(False)
        self.treeWidgetA.topLevelItem(0).setText(0, _translate("mainWindow", "0"))
        self.treeWidgetA.topLevelItem(1).setText(0, _translate("mainWindow", "5"))
        self.treeWidgetA.topLevelItem(1).child(0).setText(0, _translate("mainWindow", "New Subitem"))
        self.treeWidgetA.topLevelItem(1).child(0).child(0).setText(0, _translate("mainWindow", "New Subitem"))
        self.treeWidgetA.topLevelItem(1).child(0).child(0).child(0).setText(0, _translate("mainWindow", "New Subitem"))
        self.treeWidgetA.topLevelItem(2).setText(0, _translate("mainWindow", "6"))
        self.treeWidgetA.topLevelItem(3).setText(0, _translate("mainWindow", "7"))
        self.treeWidgetA.setSortingEnabled(__sortingEnabled)
        self.groupBox_9.setTitle(_translate("mainWindow", "输出设置"))
        self.checkBox_2.setText(_translate("mainWindow", "bone关键帧"))
        self.checkBox_5.setText(_translate("mainWindow", "只替换bip动画"))
        self.progressBar.setFormat(_translate("mainWindow", "%p%"))
        self.label_6.setText(_translate("mainWindow", "处理成功！"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("mainWindow", "批量替换模型"))
        self.groupBox_3.setTitle(_translate("mainWindow", "新的skin文件"))
        self.toolButton_3.setText(_translate("mainWindow", "..."))
        self.groupBox_4.setTitle(_translate("mainWindow", "bip路径"))
        self.toolButton_4.setText(_translate("mainWindow", "..."))
        self.groupBox_5.setTitle(_translate("mainWindow", "保存路径"))
        self.toolButton_5.setText(_translate("mainWindow", "..."))
        self.pushButton.setText(_translate("mainWindow", "应用"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "批量导入bip"))
        self.label_2.setText(_translate("mainWindow", "内部版本请勿外泄"))
        self.label_4.setText(_translate("mainWindow", "光子工作室-SN项目-美术组"))
        self.label_3.setText(_translate("mainWindow", "@2023"))
        self.BtnA_Apply.setText(_translate("mainWindow", "应用"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("mainWindow", "动画"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("mainWindow", "绑定"))
        self.label.setText(_translate("mainWindow", "输出日志"))
        self.toolButton_6.setText(_translate("mainWindow", "X"))
        self.toolButton_12.setText(_translate("mainWindow", "刷新"))
        self.menu.setTitle(_translate("mainWindow", "文件"))
        self.menu_2.setTitle(_translate("mainWindow", "窗口"))
        self.menu_3.setTitle(_translate("mainWindow", "帮助"))
        self.menu_4.setTitle(_translate("mainWindow", "关于"))
        self.label_5.setText(_translate("mainWindow", "处理进度"))
        self.toolButton_13.setText(_translate("mainWindow", "X"))
        self.textBrowser.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">test</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">tesetttt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">testttttttt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">test</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">tesetttt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">testttttttt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">test</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">tesetttt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">testttttttt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">test</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">tesetttt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">testttttttt</p></body></html>"))
        self.pushButton_4.setText(_translate("mainWindow", "清空列表"))
        self.actionshow.setText(_translate("mainWindow", "显示日志窗口"))
        self.actionhide.setText(_translate("mainWindow", "隐藏日志窗口"))
        self.actiondoc.setText(_translate("mainWindow", "帮助文档"))
        self.actionsetting.setText(_translate("mainWindow", "设置"))
        self.actionexport.setText(_translate("mainWindow", "输出目录"))
