# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'List_Farme.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PySide2 import QtCore, QtGui, QtWidgets


class List_Frame(QtWidgets.QFrame):
    def __init__(self, parent=None):
        super(List_Frame, self).__init__(parent)
        self.setupUi(self)
        self.retranslateUi(self)
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(213, 537)
        Frame.setStyleSheet("QFrame{\n"
"background-color: transparent;\n"
"\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dockWidget = QtWidgets.QDockWidget(Frame)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(9, -1, 6, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Btn_Menu = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.Btn_Menu.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}")
        self.Btn_Menu.setObjectName("Btn_Menu")
        self.horizontalLayout.addWidget(self.Btn_Menu)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Btn_Add = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.Btn_Add.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}")
        self.Btn_Add.setObjectName("Btn_Add")
        self.horizontalLayout.addWidget(self.Btn_Add)
        self.Btn_Expand = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.Btn_Expand.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}")
        self.Btn_Expand.setObjectName("Btn_Expand")
        self.horizontalLayout.addWidget(self.Btn_Expand)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CBox_Project = QtWidgets.QComboBox(self.dockWidgetContents_2)
        self.CBox_Project.setStyleSheet("QComboBox {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}")
        self.CBox_Project.setEditable(False)
        self.CBox_Project.setObjectName("CBox_Project")
        self.CBox_Project.addItem("")
        self.horizontalLayout_2.addWidget(self.CBox_Project)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(3, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.Lbl_Collection = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.Lbl_Collection.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(176, 176, 176);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"")
        self.Lbl_Collection.setObjectName("Lbl_Collection")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Lbl_Collection)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.dockWidgetContents_2)
        self.treeWidget_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_2.sizePolicy().hasHeightForWidth())
        self.treeWidget_2.setSizePolicy(sizePolicy)
        self.treeWidget_2.setStyleSheet("QTreeWidget\n"
"{\n"
"background-color: transparent;\n"
"color:rgb(255, 255, 255);\n"
"border: 0px solid rgb(17, 17, 17);\n"
"}    \n"
"QTreeWidget::item {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QTreeWidget::item:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QTreeWidget::item:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"")
        self.treeWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.treeWidget_2.setAutoExpandDelay(-1)
        self.treeWidget_2.setIndentation(6)
        self.treeWidget_2.setHeaderHidden(True)
        self.treeWidget_2.setObjectName("treeWidget_2")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        self.treeWidget_2.header().setVisible(False)
        self.treeWidget_2.header().setCascadingSectionResizes(False)
        self.treeWidget_2.header().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.treeWidget_2)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(3, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.Lbl_Folder = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.Lbl_Folder.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(176, 176, 176);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"")
        self.Lbl_Folder.setObjectName("Lbl_Folder")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Lbl_Folder)
        self.Btn_FolderAdd = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.Btn_FolderAdd.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:Right\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}")
        self.Btn_FolderAdd.setObjectName("Btn_FolderAdd")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Btn_FolderAdd)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.treeWidget = QtWidgets.QTreeWidget(self.dockWidgetContents_2)
        self.treeWidget.setStyleSheet("QTreeWidget\n"
"{\n"
"background-color: transparent;\n"
"color:rgb(255, 255, 255);\n"
"border: 0px solid rgb(17, 17, 17);\n"
"}    \n"
"QTreeWidget::item {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QTreeWidget::item:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QTreeWidget::item:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"")
        self.treeWidget.setIndentation(6)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.verticalLayout_4.addWidget(self.treeWidget)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(9, -1, 6, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_Search = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.lineEdit_Search.setStyleSheet("QLineEdit{\n"
"background-color: rgb(38, 39, 42);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(17, 17, 17);\n"
"padding: 2px;\n"
"}\n"
"")
        self.lineEdit_Search.setObjectName("lineEdit_Search")
        self.verticalLayout_2.addWidget(self.lineEdit_Search)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(120, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem3)
        self.dockWidget.setWidget(self.dockWidgetContents_2)
        self.verticalLayout_3.addWidget(self.dockWidget)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.Btn_Menu.setText(_translate("Frame", "三"))
        self.Btn_Add.setText(_translate("Frame", "Add"))
        self.Btn_Expand.setText(_translate("Frame", "田"))
        self.CBox_Project.setItemText(0, _translate("Frame", "project"))
        self.Lbl_Collection.setText(_translate("Frame", "收藏夹"))
        self.treeWidget_2.headerItem().setText(0, _translate("Frame", "Name"))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, _translate("Frame", "New Item"))
        self.treeWidget_2.topLevelItem(1).setText(0, _translate("Frame", "New Item"))
        self.treeWidget_2.topLevelItem(2).setText(0, _translate("Frame", "New Item"))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        self.Lbl_Folder.setText(_translate("Frame", "文件夹"))
        self.Btn_FolderAdd.setText(_translate("Frame", "Add"))
        self.treeWidget.headerItem().setText(0, _translate("Frame", "Name"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Frame", "New Item"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Frame", "New Item"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("Frame", "New Item"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("Frame", "New Item"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
