# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_root_motion.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(422, 478)
        Frame.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setContentsMargins(6, 9, 6, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_7 = QtWidgets.QFrame(Frame)
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_4 = QtWidgets.QFrame(self.frame_7)
        self.frame_4.setStyleSheet("QFrame#frame_4{\n"
"    background-color:rgb(65, 65, 65);\n"
"    border-radius:10px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.groupBox = QtWidgets.QGroupBox(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"background-color:rgb(90, 90, 90);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(40, 40, 40);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"background-color:rgb(100, 100, 100);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(150, 150, 150);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:pressed {\n"
"background-color:rgb(110, 110, 110);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.Btn_root_pick = QtWidgets.QToolButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_root_pick.sizePolicy().hasHeightForWidth())
        self.Btn_root_pick.setSizePolicy(sizePolicy)
        self.Btn_root_pick.setObjectName("Btn_root_pick")
        self.horizontalLayout.addWidget(self.Btn_root_pick)
        self.horizontalLayout_13.addWidget(self.groupBox)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_8.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_7)
        self.frame_6.setStyleSheet("QFrame#frame_6{\n"
"    background-color:rgb(65, 65, 65);\n"
"    border-radius:10px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"background-color:rgb(90, 90, 90);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(40, 40, 40);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"background-color:rgb(100, 100, 100);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(150, 150, 150);\n"
"padding: 2px;\n"
"}\n"
"QLineEdit:pressed {\n"
"background-color:rgb(110, 110, 110);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(70, 70, 70);\n"
"padding: 2px;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.Btn_Pelvis_pick = QtWidgets.QToolButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Pelvis_pick.sizePolicy().hasHeightForWidth())
        self.Btn_Pelvis_pick.setSizePolicy(sizePolicy)
        self.Btn_Pelvis_pick.setObjectName("Btn_Pelvis_pick")
        self.horizontalLayout_2.addWidget(self.Btn_Pelvis_pick)
        self.horizontalLayout_15.addWidget(self.groupBox_2)
        self.horizontalLayout_8.addWidget(self.frame_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.frame_3 = QtWidgets.QFrame(self.frame_7)
        self.frame_3.setStyleSheet("QFrame#frame_3{\n"
"    background-color:rgb(65, 65, 65);\n"
"    border-radius:10px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_13 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cBox_posX = QtWidgets.QCheckBox(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_posX.setFont(font)
        self.cBox_posX.setObjectName("cBox_posX")
        self.horizontalLayout_9.addWidget(self.cBox_posX)
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_13)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_9.addWidget(self.radioButton_6)
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_13)
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_9.addWidget(self.radioButton_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.verticalLayout_9.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.cBox_posY = QtWidgets.QCheckBox(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_posY.setFont(font)
        self.cBox_posY.setChecked(True)
        self.cBox_posY.setObjectName("cBox_posY")
        self.horizontalLayout_16.addWidget(self.cBox_posY)
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_14)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_16.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_14)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_16.addWidget(self.radioButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem1)
        self.verticalLayout_9.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.cBox_posZ = QtWidgets.QCheckBox(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_posZ.setFont(font)
        self.cBox_posZ.setObjectName("cBox_posZ")
        self.horizontalLayout_18.addWidget(self.cBox_posZ)
        self.radioButton_9 = QtWidgets.QRadioButton(self.frame_15)
        self.radioButton_9.setChecked(True)
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout_18.addWidget(self.radioButton_9)
        self.radioButton_8 = QtWidgets.QRadioButton(self.frame_15)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_18.addWidget(self.radioButton_8)
        self.radioButton_10 = QtWidgets.QRadioButton(self.frame_15)
        self.radioButton_10.setObjectName("radioButton_10")
        self.horizontalLayout_18.addWidget(self.radioButton_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.spinBox_frame_reference = QtWidgets.QSpinBox(self.frame_15)
        self.spinBox_frame_reference.setMinimum(-99999999)
        self.spinBox_frame_reference.setMaximum(999999999)
        self.spinBox_frame_reference.setObjectName("spinBox_frame_reference")
        self.horizontalLayout_12.addWidget(self.spinBox_frame_reference)
        self.Btn_frame_reference_pick = QtWidgets.QToolButton(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_frame_reference_pick.sizePolicy().hasHeightForWidth())
        self.Btn_frame_reference_pick.setSizePolicy(sizePolicy)
        self.Btn_frame_reference_pick.setObjectName("Btn_frame_reference_pick")
        self.horizontalLayout_12.addWidget(self.Btn_frame_reference_pick)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_12)
        self.radioBtn_ZAxis_zero = QtWidgets.QCheckBox(self.frame_15)
        self.radioBtn_ZAxis_zero.setObjectName("radioBtn_ZAxis_zero")
        self.horizontalLayout_18.addWidget(self.radioBtn_ZAxis_zero)
        self.verticalLayout_9.addWidget(self.frame_15)
        self.verticalLayout_14.addWidget(self.groupBox_3)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame_7)
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
"    background-color:rgb(65, 65, 65);\n"
"    border-radius:10px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_10.addWidget(self.radioButton)
        self.radioBtn_custom_frame = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioBtn_custom_frame.setObjectName("radioBtn_custom_frame")
        self.horizontalLayout_10.addWidget(self.radioBtn_custom_frame)
        self.radioBtn_current_frame = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioBtn_current_frame.setObjectName("radioBtn_current_frame")
        self.horizontalLayout_10.addWidget(self.radioBtn_current_frame)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.spinBox_frame_start = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_frame_start.setMinimum(-99999999)
        self.spinBox_frame_start.setMaximum(999999999)
        self.spinBox_frame_start.setObjectName("spinBox_frame_start")
        self.horizontalLayout_6.addWidget(self.spinBox_frame_start)
        self.Btn_frame_start_pick = QtWidgets.QToolButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_frame_start_pick.sizePolicy().hasHeightForWidth())
        self.Btn_frame_start_pick.setSizePolicy(sizePolicy)
        self.Btn_frame_start_pick.setObjectName("Btn_frame_start_pick")
        self.horizontalLayout_6.addWidget(self.Btn_frame_start_pick)
        self.horizontalLayout_5.addWidget(self.groupBox_5)
        self.line_2 = QtWidgets.QFrame(self.groupBox_4)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.spinBox_frame_end = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_frame_end.setMinimum(-99999999)
        self.spinBox_frame_end.setMaximum(999999999)
        self.spinBox_frame_end.setObjectName("spinBox_frame_end")
        self.horizontalLayout_7.addWidget(self.spinBox_frame_end)
        self.Btn_frame_end_pick = QtWidgets.QToolButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_frame_end_pick.sizePolicy().hasHeightForWidth())
        self.Btn_frame_end_pick.setSizePolicy(sizePolicy)
        self.Btn_frame_end_pick.setObjectName("Btn_frame_end_pick")
        self.horizontalLayout_7.addWidget(self.Btn_frame_end_pick)
        self.horizontalLayout_5.addWidget(self.groupBox_6)
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.Btn_frame_range_pick = QtWidgets.QToolButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_frame_range_pick.sizePolicy().hasHeightForWidth())
        self.Btn_frame_range_pick.setSizePolicy(sizePolicy)
        self.Btn_frame_range_pick.setObjectName("Btn_frame_range_pick")
        self.horizontalLayout_5.addWidget(self.Btn_frame_range_pick)
        self.horizontalLayout_5.setStretch(4, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.frame_7)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Btn_Apply = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Apply.sizePolicy().hasHeightForWidth())
        self.Btn_Apply.setSizePolicy(sizePolicy)
        self.Btn_Apply.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Btn_Apply.setFont(font)
        self.Btn_Apply.setStyleSheet("QToolButton {\n"
"    background-color:rgb(40, 105, 254);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QToolButton:hover {\n"
"    background-color:rgb(14, 59, 229);\n"
"border-radius: 6px;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(1, 33, 154);\n"
"border-radius: 6px;\n"
"    border-style: inset;\n"
"}\n"
"\n"
"")
        self.Btn_Apply.setObjectName("Btn_Apply")
        self.horizontalLayout_4.addWidget(self.Btn_Apply)
        self.horizontalLayout_4.setStretch(0, 5)
        self.verticalLayout_3.addWidget(self.frame)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(Frame)
        self.frame_9.setStyleSheet("")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(2)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(120, 150, 254);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(120, 150, 254);\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(120, 150, 254);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_17.addLayout(self.verticalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.Btn_About = QtWidgets.QToolButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_About.sizePolicy().hasHeightForWidth())
        self.Btn_About.setSizePolicy(sizePolicy)
        self.Btn_About.setObjectName("Btn_About")
        self.verticalLayout_6.addWidget(self.Btn_About)
        self.horizontalLayout_17.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.Btn_language_switch = QtWidgets.QToolButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_language_switch.sizePolicy().hasHeightForWidth())
        self.Btn_language_switch.setSizePolicy(sizePolicy)
        self.Btn_language_switch.setObjectName("Btn_language_switch")
        self.verticalLayout_7.addWidget(self.Btn_language_switch)
        self.horizontalLayout_17.addLayout(self.verticalLayout_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout.addWidget(self.frame_9)
        self.progressBar = QtWidgets.QProgressBar(Frame)
        self.progressBar.setStyleSheet("QProgressBar\n"
"{\n"
"background-color: rgb(120, 120, 120);\n"
"color:rgb(255, 255, 255);\n"
"min-height: 15px;\n"
"max-height: 15px;\n"
"border-radius: 6px;\n"
"}    \n"
"QProgressBar::chunk {\n"
"background-color: rgb(60, 200, 0);\n"
"    border-radius: 6px;\n"
"\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "SN_Root_Motion"))
        self.groupBox.setTitle(_translate("Frame", "根骨骼"))
        self.lineEdit.setText(_translate("Frame", "root"))
        self.Btn_root_pick.setText(_translate("Frame", "↙"))
        self.groupBox_2.setTitle(_translate("Frame", "质心"))
        self.lineEdit_2.setText(_translate("Frame", "Bip001"))
        self.Btn_Pelvis_pick.setText(_translate("Frame", "↙"))
        self.groupBox_3.setTitle(_translate("Frame", "提取位移轴"))
        self.cBox_posX.setText(_translate("Frame", "X"))
        self.radioButton_6.setText(_translate("Frame", "首帧"))
        self.radioButton_5.setText(_translate("Frame", "无偏移"))
        self.cBox_posY.setText(_translate("Frame", "Y"))
        self.radioButton_3.setText(_translate("Frame", "首帧"))
        self.radioButton_2.setText(_translate("Frame", "无偏移"))
        self.cBox_posZ.setText(_translate("Frame", "Z"))
        self.radioButton_9.setText(_translate("Frame", "首帧"))
        self.radioButton_8.setText(_translate("Frame", "无偏移"))
        self.radioButton_10.setText(_translate("Frame", "获取帧偏移值"))
        self.Btn_frame_reference_pick.setText(_translate("Frame", "指定"))
        self.radioBtn_ZAxis_zero.setText(_translate("Frame", "Z轴不小于0"))
        self.radioButton.setText(_translate("Frame", "时间滑块范围"))
        self.radioBtn_custom_frame.setText(_translate("Frame", "自定义帧数范围"))
        self.radioBtn_current_frame.setText(_translate("Frame", "当前帧"))
        self.groupBox_5.setTitle(_translate("Frame", "开始帧:       "))
        self.Btn_frame_start_pick.setText(_translate("Frame", "↙"))
        self.groupBox_6.setTitle(_translate("Frame", "结束帧:       "))
        self.Btn_frame_end_pick.setText(_translate("Frame", "↙"))
        self.Btn_frame_range_pick.setText(_translate("Frame", "时间滑块范围"))
        self.Btn_Apply.setText(_translate("Frame", "      应用      "))
        self.label_3.setText(_translate("Frame", "内部版本请勿外泄"))
        self.label.setText(_translate("Frame", "光子工作室-SN项目-美术组"))
        self.label_2.setText(_translate("Frame", "@2023"))
        self.Btn_About.setText(_translate("Frame", "关于"))
        self.Btn_language_switch.setText(_translate("Frame", "中文/EN"))
