# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Card_Farme.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Card_Frame(QtWidgets.QFrame):
    def __init__(self, parent=None):
        super(Card_Frame, self).__init__(parent)
        self.setupUi(self)



    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(215, 677)
        Frame.setStyleSheet("QFrame{\n"
"    background-color:rgba(10,225,225,0);\n"
"    border-radius:0px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color:rgba(10,225,225,0);\n"
"    border-radius:0px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setEnabled(False)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, 10, 6, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color:argb(10, 10, 10,40);\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:argb(10, 10, 10,80);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  argb(10, 10, 10,150);\n"
"    border-style: inset;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_16.addWidget(self.pushButton_2)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(176, 176, 176);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout_16.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(176, 176, 176);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_16.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_16)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_2.setStyleSheet("QCheckBox{\n"
"    background-color:transparent;\n"
"    color:rgb(176, 176, 176);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"")
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_4.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setStyleSheet("QCheckBox{\n"
"    background-color:transparent;\n"
"    color:rgb(176, 176, 176);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_4.addWidget(self.checkBox)
        self.horizontalSlider = QtWidgets.QSlider(self.frame)
        self.horizontalSlider.setMinimum(-50)
        self.horizontalSlider.setMaximum(150)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_4.addWidget(self.horizontalSlider)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(6, 15, 6, 6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color:rgb(0, 114, 239);\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 164, 239);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 214, 239);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_6.addWidget(self.pushButton_5)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.pushButton.setText(_translate("Frame", "选择类型"))
        self.pushButton_3.setText(_translate("Frame", "PushButton"))
        self.pushButton_2.setText(_translate("Frame", "文件信息"))
        self.label.setText(_translate("Frame", "TextLabel"))
        self.label_2.setText(_translate("Frame", "TextLabel"))
        self.pushButton_4.setText(_translate("Frame", "PushButton"))
        self.checkBox_2.setText(_translate("Frame", "绝对位置"))
        self.checkBox.setText(_translate("Frame", "当前时间插入"))
        self.pushButton_5.setText(_translate("Frame", "应用"))
