# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PoseWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(947, 564)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWindow#MainWindow\n"
"{\n"
"background-color:rgb(68, 68, 68);\n"
"}    \n"
"")
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.library_frame = QtWidgets.QFrame(self.centralwidget)
        self.library_frame.setStyleSheet("QFrame#library_frame{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"border: 0px ;\n"
"background-color:rgb(60, 60, 60);\n"
"width:6px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"background:rgb(225,225, 225);\n"
"min-height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"background: rgb(255, 0, 0);\n"
"       height: 0px;\n"
"     subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"#QScrollBar::sub-line:vertical {\n"
" background: rgb(0, 255, 17);\n"
"    height: 0 px;\n"
"     subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"    }")
        self.library_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.library_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.library_frame.setObjectName("library_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.library_frame)
        self.verticalLayout_11.setContentsMargins(0, 8, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.UI_Library_frame = QtWidgets.QFrame(self.library_frame)
        self.UI_Library_frame.setStyleSheet("")
        self.UI_Library_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UI_Library_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UI_Library_frame.setObjectName("UI_Library_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.UI_Library_frame)
        self.verticalLayout_6.setContentsMargins(8, 0, 0, 8)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, 0, 8, 0)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.UI_Library_frame)
        self.pushButton.setMinimumSize(QtCore.QSize(23, 23))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.UI_Library_frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(23, 23))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.Btn_Creat = QtWidgets.QPushButton(self.UI_Library_frame)
        self.Btn_Creat.setMinimumSize(QtCore.QSize(23, 23))
        self.Btn_Creat.setStyleSheet("QPushButton {\n"
"    background-color:rgb(40, 105, 254);\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(14, 59, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(1, 33, 154);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"")
        self.Btn_Creat.setObjectName("Btn_Creat")
        self.horizontalLayout_4.addWidget(self.Btn_Creat)
        self.lineEdit = QtWidgets.QLineEdit(self.UI_Library_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(23, 23))
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"background-color:rgb(42, 42, 42);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(25, 25, 25);\n"
"padding: 2px;\n"
"}\n"
"")
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.frame_2 = QtWidgets.QFrame(self.UI_Library_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 4, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setStyleSheet("QTableWidget\n"
"{\n"
"background-color: transparent;\n"
"color:rgb(255, 255, 255);\n"
"border: 0px solid rgb(17, 17, 17);\n"
"}    \n"
"QTableWidget::item {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QTableWidget::item:hover {\n"
"    background-color:  rgb(40, 105, 254);\n"
"}\n"
"QTableWidget::item:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color:  rgb(40, 105, 254);\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableWidget.setIconSize(QtCore.QSize(0, 0))
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setRowCount(14)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.verticalLayout_10.addWidget(self.tableWidget)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.horizontalLayout_2.addWidget(self.UI_Library_frame)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.horizontalLayout_6.addWidget(self.library_frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("QStatusBar {min-height: -10; background-color: transparent; }")
        self.statusbar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dockWidget.setWindowTitle("")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtWidgets.QFrame(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(10, 8, 6, 8)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Btn_Menu = QtWidgets.QPushButton(self.frame)
        self.Btn_Menu.setEnabled(True)
        self.Btn_Menu.setMinimumSize(QtCore.QSize(23, 23))
        self.Btn_Menu.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}")
        self.Btn_Menu.setObjectName("Btn_Menu")
        self.horizontalLayout_10.addWidget(self.Btn_Menu)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.Btn_Add = QtWidgets.QPushButton(self.frame)
        self.Btn_Add.setMinimumSize(QtCore.QSize(23, 23))
        self.Btn_Add.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}")
        self.Btn_Add.setObjectName("Btn_Add")
        self.horizontalLayout_10.addWidget(self.Btn_Add)
        self.Btn_Expand = QtWidgets.QPushButton(self.frame)
        self.Btn_Expand.setMinimumSize(QtCore.QSize(23, 23))
        self.Btn_Expand.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}")
        self.Btn_Expand.setObjectName("Btn_Expand")
        self.horizontalLayout_10.addWidget(self.Btn_Expand)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Lbl_Folder = QtWidgets.QLabel(self.frame_8)
        self.Lbl_Folder.setMinimumSize(QtCore.QSize(28, 28))
        self.Lbl_Folder.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(225, 225, 225);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"")
        self.Lbl_Folder.setObjectName("Lbl_Folder")
        self.horizontalLayout_12.addWidget(self.Lbl_Folder)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.Btn_HomePagge = QtWidgets.QPushButton(self.frame_8)
        self.Btn_HomePagge.setMinimumSize(QtCore.QSize(23, 23))
        self.Btn_HomePagge.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(225, 225, 225);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"")
        self.Btn_HomePagge.setObjectName("Btn_HomePagge")
        self.horizontalLayout_12.addWidget(self.Btn_HomePagge)
        self.verticalLayout_15.addLayout(self.horizontalLayout_12)
        self.verticalLayout.addWidget(self.frame_8)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_2.sizePolicy().hasHeightForWidth())
        self.treeWidget_2.setSizePolicy(sizePolicy)
        self.treeWidget_2.setStyleSheet("QTreeWidget\n"
"{\n"
"background-color: transparent;\n"
"color:rgb(255, 255, 255);\n"
"border: 0px solid rgb(17, 17, 17);\n"
"}    \n"
"QTreeWidget::item {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QTreeWidget::item:hover {\n"
"    background-color: rgb(52, 95, 251);\n"
"}\n"
"QTreeWidget::item:pressed {\n"
"    background-color: rgb(10, 50, 205);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"\n"
"QTreeWidget::item:selected {\n"
"    background-color: rgb(52, 95, 251);\n"
"    border-style: inset;\n"
"}\n"
"")
        self.treeWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeWidget_2.setIndentation(6)
        self.treeWidget_2.setHeaderHidden(True)
        self.treeWidget_2.setObjectName("treeWidget_2")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        self.verticalLayout_17.addWidget(self.treeWidget_2)
        self.verticalLayout.addLayout(self.verticalLayout_17)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_Search = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Search.setMinimumSize(QtCore.QSize(23, 23))
        self.lineEdit_Search.setStyleSheet("QLineEdit{\n"
"background-color:rgb(42, 42, 42);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px; \n"
"border: 1px solid rgb(25, 25, 25);\n"
"padding: 2px;\n"
"}\n"
"")
        self.lineEdit_Search.setObjectName("lineEdit_Search")
        self.verticalLayout_3.addWidget(self.lineEdit_Search)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(257, 4, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout_5.addWidget(self.frame)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockWidget_top = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_top.sizePolicy().hasHeightForWidth())
        self.dockWidget_top.setSizePolicy(sizePolicy)
        self.dockWidget_top.setMinimumSize(QtCore.QSize(80, 23))
        self.dockWidget_top.setMaximumSize(QtCore.QSize(524287, 23))
        self.dockWidget_top.setObjectName("dockWidget_top")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.Btn_win_min = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.Btn_win_min.setMinimumSize(QtCore.QSize(23, 23))
        self.Btn_win_min.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}")
        self.Btn_win_min.setObjectName("Btn_win_min")
        self.horizontalLayout_11.addWidget(self.Btn_win_min)
        self.Btn_win_max = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.Btn_win_max.setMinimumSize(QtCore.QSize(23, 23))
        self.Btn_win_max.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}")
        self.Btn_win_max.setObjectName("Btn_win_max")
        self.horizontalLayout_11.addWidget(self.Btn_win_max)
        self.Btn_win_close = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.Btn_win_close.setMinimumSize(QtCore.QSize(23, 23))
        self.Btn_win_close.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}")
        self.Btn_win_close.setObjectName("Btn_win_close")
        self.horizontalLayout_11.addWidget(self.Btn_win_close)
        self.dockWidget_top.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_top)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_3 = QtWidgets.QFrame(self.dockWidgetContents_3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setContentsMargins(5, 0, 10, 8)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setStyleSheet("QFrame{\n"
"background-color:rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setMinimumSize(QtCore.QSize(23, 23))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(225, 225, 225);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(210, 210, 210);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.verticalLayout_8.addWidget(self.frame_7)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color:argb(10, 10, 10,40);\n"
"    color: rgb(225, 225, 225);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:argb(10, 10, 10,40);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: argb(10, 10, 10,40);\n"
"    border-style: inset;\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_20.addWidget(self.pushButton_4)
        self.verticalLayout_8.addLayout(self.verticalLayout_20)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setStyleSheet("QFrame{\n"
"background-color:rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(5, 0, -1, -1)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setMinimumSize(QtCore.QSize(23, 23))
        self.label.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(225, 225, 225);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(15, -1, -1, -1)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Lbl_Name = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lbl_Name.sizePolicy().hasHeightForWidth())
        self.Lbl_Name.setSizePolicy(sizePolicy)
        self.Lbl_Name.setMinimumSize(QtCore.QSize(23, 23))
        self.Lbl_Name.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(176, 176, 176);\n"
"\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"")
        self.Lbl_Name.setObjectName("Lbl_Name")
        self.verticalLayout_9.addWidget(self.Lbl_Name)
        self.Lbl_ObjCount = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lbl_ObjCount.sizePolicy().hasHeightForWidth())
        self.Lbl_ObjCount.setSizePolicy(sizePolicy)
        self.Lbl_ObjCount.setMinimumSize(QtCore.QSize(23, 23))
        self.Lbl_ObjCount.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(176, 176, 176);\n"
"\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"")
        self.Lbl_ObjCount.setObjectName("Lbl_ObjCount")
        self.verticalLayout_9.addWidget(self.Lbl_ObjCount)
        self.Lbl_Path = QtWidgets.QLabel(self.frame_4)
        self.Lbl_Path.setMinimumSize(QtCore.QSize(23, 23))
        self.Lbl_Path.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(176, 176, 176);\n"
"\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"")
        self.Lbl_Path.setObjectName("Lbl_Path")
        self.verticalLayout_9.addWidget(self.Lbl_Path)
        self.verticalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_8.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("QFrame{\n"
"background-color:rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setMinimumSize(QtCore.QSize(23, 23))
        self.label_2.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(225, 225, 225);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(15, -1, -1, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_3.setMinimumSize(QtCore.QSize(23, 23))
        self.checkBox_3.setStyleSheet("QCheckBox{\n"
"    background-color:transparent;\n"
"    color:rgb(176, 176, 176);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"")
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_13.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_4.setMinimumSize(QtCore.QSize(23, 23))
        self.checkBox_4.setStyleSheet("QCheckBox{\n"
"    background-color:transparent;\n"
"    color:rgb(176, 176, 176);\n"
"\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"    text-align:left\n"
"}\n"
"")
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_13.addWidget(self.checkBox_4)
        self.verticalLayout_12.addLayout(self.verticalLayout_13)
        self.verticalLayout_8.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setStyleSheet("QFrame{\n"
"background-color:rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.frame_6)
        self.horizontalSlider_2.setMinimum(-50)
        self.horizontalSlider_2.setMaximum(150)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.verticalLayout_14.addWidget(self.horizontalSlider_2)
        self.verticalLayout_8.addWidget(self.frame_6)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(6)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.Btn_Apply = QtWidgets.QPushButton(self.frame_3)
        self.Btn_Apply.setMinimumSize(QtCore.QSize(30, 30))
        self.Btn_Apply.setStyleSheet("QPushButton {\n"
"    background-color:rgb(40, 105, 254);\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-radius: 3px;\n"
"    border-color: beige;\n"
"    padding: 2px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(14, 59, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(1, 33, 154);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"")
        self.Btn_Apply.setObjectName("Btn_Apply")
        self.verticalLayout_23.addWidget(self.Btn_Apply)
        self.verticalLayout_8.addLayout(self.verticalLayout_23)
        spacerItem5 = QtWidgets.QSpacerItem(180, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.verticalLayout_16.addWidget(self.frame_3)
        self.dockWidget_2.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "add"))
        self.pushButton_3.setText(_translate("MainWindow", "田"))
        self.Btn_Creat.setText(_translate("MainWindow", "添加"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Column"))
        self.Btn_Menu.setText(_translate("MainWindow", "三"))
        self.Btn_Add.setText(_translate("MainWindow", "Add"))
        self.Btn_Expand.setText(_translate("MainWindow", "田"))
        self.Lbl_Folder.setText(_translate("MainWindow", "文件夹"))
        self.Btn_HomePagge.setText(_translate("MainWindow", "首页"))
        self.treeWidget_2.headerItem().setText(0, _translate("MainWindow", "New Column"))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, _translate("MainWindow", "New Item"))
        self.treeWidget_2.topLevelItem(1).setText(0, _translate("MainWindow", "New Item"))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        self.Btn_win_min.setText(_translate("MainWindow", "一"))
        self.Btn_win_max.setText(_translate("MainWindow", "口"))
        self.Btn_win_close.setText(_translate("MainWindow", " X"))
        self.pushButton_2.setText(_translate("MainWindow", "选择类型"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "文件信息"))
        self.Lbl_Name.setText(_translate("MainWindow", "name"))
        self.Lbl_ObjCount.setText(_translate("MainWindow", "TextLabel"))
        self.Lbl_Path.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "应用方式"))
        self.checkBox_3.setText(_translate("MainWindow", "绝对位置"))
        self.checkBox_4.setText(_translate("MainWindow", "当前时间插入"))
        self.Btn_Apply.setText(_translate("MainWindow", "应用"))
